-- SoundConnect Studio domain additive rollout.
--
-- Prerequisites:
--   * Reconcile this script with an authoritative schema-only dump before production.
--   * Run with a role allowed to install/own btree_gist, or pre-provision that extension.
--   * Run psql with ON_ERROR_STOP=1.
--
-- The migration is intentionally additive and rerunnable. It does not import Flutter
-- mock data. UUIDs are generated by the application; deterministic UUID literals are
-- used only for global seed rows.

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------------
-- Stable public user code
-- ---------------------------------------------------------------------------

ALTER TABLE tbl_user
    ADD COLUMN IF NOT EXISTS public_code varchar(23);

DO $$
BEGIN
    IF (
        SELECT character_maximum_length
          FROM information_schema.columns
         WHERE table_schema = current_schema()
           AND table_name = 'tbl_user'
           AND column_name = 'public_code'
    ) IS DISTINCT FROM 23 THEN
        DROP TRIGGER IF EXISTS trg_user_public_code ON tbl_user;
        ALTER TABLE tbl_user ALTER COLUMN public_code TYPE varchar(23);
    END IF;
END
$$;

ALTER TABLE tbl_user
    ALTER COLUMN public_code DROP DEFAULT;

CREATE OR REPLACE FUNCTION soundconnect_assign_user_public_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate varchar(23);
BEGIN
    IF TG_OP = 'INSERT' AND (NEW.public_code IS NULL OR btrim(NEW.public_code) = '') THEN
        LOOP
            candidate := 'SC-' || upper(left(replace(gen_random_uuid()::text, '-', ''), 20));
            EXIT WHEN NOT EXISTS (SELECT 1 FROM tbl_user WHERE public_code = candidate);
        END LOOP;
        NEW.public_code := candidate;
    ELSIF TG_OP = 'UPDATE' AND (OLD.public_code IS NULL OR btrim(OLD.public_code) = '')
          AND (NEW.public_code IS NULL OR btrim(NEW.public_code) = '') THEN
        LOOP
            candidate := 'SC-' || upper(left(replace(gen_random_uuid()::text, '-', ''), 20));
            EXIT WHEN NOT EXISTS (SELECT 1 FROM tbl_user WHERE public_code = candidate);
        END LOOP;
        NEW.public_code := candidate;
    ELSIF TG_OP = 'UPDATE' AND NEW.public_code IS DISTINCT FROM OLD.public_code THEN
        RAISE EXCEPTION 'user public_code is immutable'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_user_public_code_immutable';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_user_public_code ON tbl_user;
CREATE TRIGGER trg_user_public_code
BEFORE INSERT OR UPDATE OF public_code ON tbl_user
FOR EACH ROW
EXECUTE FUNCTION soundconnect_assign_user_public_code();

-- Assign through the same trigger used by future inserts. Random UUID-derived
-- values match the application format and are collision-checked before assignment.
UPDATE tbl_user
   SET public_code = NULL
 WHERE public_code IS NULL OR btrim(public_code) = '';

ALTER TABLE tbl_user
    ALTER COLUMN public_code SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_public_code
    ON tbl_user (public_code);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'tbl_user'::regclass
           AND conname = 'ck_user_public_code_format'
    ) THEN
        ALTER TABLE tbl_user
            ADD CONSTRAINT ck_user_public_code_format
            CHECK (public_code ~ '^SC-[0-9A-F]{20}$');
    END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- Studio profile additions and ordered Spotify catalog
-- ---------------------------------------------------------------------------

ALTER TABLE tbl_studio_profile
    ADD COLUMN IF NOT EXISTS time_zone varchar(64),
    ADD COLUMN IF NOT EXISTS version bigint,
    ADD COLUMN IF NOT EXISTS spotify_tracks jsonb,
    ADD COLUMN IF NOT EXISTS city_id uuid,
    ADD COLUMN IF NOT EXISTS district_id uuid,
    ADD COLUMN IF NOT EXISTS neighborhood_id uuid;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_studio_profile_city') THEN
        ALTER TABLE tbl_studio_profile ADD CONSTRAINT fk_studio_profile_city
            FOREIGN KEY (city_id) REFERENCES tbl_city (id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_studio_profile_district') THEN
        ALTER TABLE tbl_studio_profile ADD CONSTRAINT fk_studio_profile_district
            FOREIGN KEY (district_id) REFERENCES tbl_district (id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_studio_profile_neighborhood') THEN
        ALTER TABLE tbl_studio_profile ADD CONSTRAINT fk_studio_profile_neighborhood
            FOREIGN KEY (neighborhood_id) REFERENCES tbl_neighborhood (id) ON DELETE RESTRICT;
    END IF;
END
$$;

-- Existing legacy Studio profiles may not yet have a complete district and
-- neighborhood. New approved applications always provision all three values;
-- NOT NULL can be enforced in a later cleanup rollout after legacy backfill.

CREATE TABLE IF NOT EXISTS tbl_studio_applications (
    id uuid PRIMARY KEY,
    created_at timestamp,
    updated_at timestamp,
    applicant_id uuid NOT NULL,
    studio_name varchar(100) NOT NULL,
    studio_address varchar(255) NOT NULL,
    phone varchar(15) NOT NULL,
    city_id uuid NOT NULL,
    district_id uuid NOT NULL,
    neighborhood_id uuid NOT NULL,
    status varchar(16) NOT NULL,
    application_date timestamp NOT NULL,
    decision_date timestamp,
    reviewed_by_id uuid,
    rejection_reason varchar(500),
    CONSTRAINT fk_studio_application_applicant
        FOREIGN KEY (applicant_id) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_application_city
        FOREIGN KEY (city_id) REFERENCES tbl_city (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_application_district
        FOREIGN KEY (district_id) REFERENCES tbl_district (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_application_neighborhood
        FOREIGN KEY (neighborhood_id) REFERENCES tbl_neighborhood (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_application_reviewer
        FOREIGN KEY (reviewed_by_id) REFERENCES tbl_user (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_studio_application_pending_applicant
    ON tbl_studio_applications (applicant_id)
    WHERE status = 'PENDING';

DROP INDEX IF EXISTS ix_studio_application_status_date;

CREATE INDEX IF NOT EXISTS ix_studio_application_status_date_id
    ON tbl_studio_applications (status, application_date, id);

CREATE INDEX IF NOT EXISTS ix_studio_application_applicant_date_id
    ON tbl_studio_applications (applicant_id, application_date DESC, id DESC);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_studio_application_status') THEN
        ALTER TABLE tbl_studio_applications ADD CONSTRAINT ck_studio_application_status
            CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_studio_application_decision') THEN
        ALTER TABLE tbl_studio_applications ADD CONSTRAINT ck_studio_application_decision CHECK (
            (status = 'PENDING' AND decision_date IS NULL AND reviewed_by_id IS NULL AND rejection_reason IS NULL)
            OR (status = 'APPROVED' AND decision_date IS NOT NULL AND reviewed_by_id IS NOT NULL AND rejection_reason IS NULL)
            OR (status = 'REJECTED' AND decision_date IS NOT NULL AND reviewed_by_id IS NOT NULL AND rejection_reason IS NOT NULL)
        );
    END IF;
END
$$;

-- The new rejected-registration state is one character longer than the
-- previous longest UserStatus value. Widen only legacy bounded text columns;
-- unbounded text/varchar columns need no change and wider columns are kept.
DO $$
DECLARE
    user_status_data_type text;
    user_status_max_length integer;
BEGIN
    SELECT data_type, character_maximum_length
      INTO user_status_data_type, user_status_max_length
      FROM information_schema.columns
     WHERE table_schema = current_schema()
       AND table_name = 'tbl_user'
       AND column_name = 'status';

    IF user_status_data_type IN ('character varying', 'character')
       AND user_status_max_length IS NOT NULL
       AND user_status_max_length < 32 THEN
        ALTER TABLE tbl_user
            ALTER COLUMN status TYPE varchar(32) USING status::text;
    END IF;
END
$$;

-- Close legacy registration accounts whose most recent Studio application was
-- already rejected. Previously these users remained PENDING_STUDIO_REQUEST and
-- every later login incorrectly claimed that review was still in progress.
-- Active multi-role users are deliberately excluded by the status predicate.
UPDATE tbl_user applicant
   SET status = 'REJECTED_STUDIO_REQUEST',
       updated_at = CURRENT_TIMESTAMP
 WHERE applicant.status = 'PENDING_STUDIO_REQUEST'
   AND (
       SELECT application.status
         FROM tbl_studio_applications application
        WHERE application.applicant_id = applicant.id
        ORDER BY application.application_date DESC, application.id DESC
        LIMIT 1
   ) = 'REJECTED';

UPDATE tbl_studio_profile
   SET time_zone = 'Europe/Istanbul'
 WHERE time_zone IS NULL OR btrim(time_zone) = '';

UPDATE tbl_studio_profile
   SET version = 0
 WHERE version IS NULL;

UPDATE tbl_studio_profile
   SET spotify_tracks = '[]'::jsonb
 WHERE spotify_tracks IS NULL;

ALTER TABLE tbl_studio_profile
    ALTER COLUMN time_zone SET DEFAULT 'Europe/Istanbul',
    ALTER COLUMN time_zone SET NOT NULL,
    ALTER COLUMN version SET DEFAULT 0,
    ALTER COLUMN version SET NOT NULL,
    ALTER COLUMN spotify_tracks SET DEFAULT '[]'::jsonb,
    ALTER COLUMN spotify_tracks SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'tbl_studio_profile'::regclass
           AND conname = 'ck_studio_profile_time_zone_not_blank'
    ) THEN
        ALTER TABLE tbl_studio_profile
            ADD CONSTRAINT ck_studio_profile_time_zone_not_blank
            CHECK (btrim(time_zone) <> '');
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'tbl_studio_profile'::regclass
           AND conname = 'ck_studio_profile_version_non_negative'
    ) THEN
        ALTER TABLE tbl_studio_profile
            ADD CONSTRAINT ck_studio_profile_version_non_negative
            CHECK (version >= 0);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'tbl_studio_profile'::regclass
           AND conname = 'ck_studio_profile_spotify_tracks_array'
    ) THEN
        ALTER TABLE tbl_studio_profile
            ADD CONSTRAINT ck_studio_profile_spotify_tracks_array
            CHECK (
                jsonb_typeof(spotify_tracks) = 'array'
                AND jsonb_array_length(spotify_tracks) <= 50
            );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS studio_profile_spotify_tracks (
    studio_profile_id uuid NOT NULL,
    position integer NOT NULL,
    track_id varchar(64) NOT NULL,
    CONSTRAINT pk_studio_profile_spotify_tracks
        PRIMARY KEY (studio_profile_id, position),
    CONSTRAINT fk_studio_spotify_track_profile
        FOREIGN KEY (studio_profile_id)
        REFERENCES tbl_studio_profile (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_studio_spotify_track
        UNIQUE (studio_profile_id, track_id),
    CONSTRAINT ck_studio_spotify_track_order
        CHECK (position BETWEEN 0 AND 49),
    CONSTRAINT ck_studio_spotify_track_id_not_blank
        CHECK (btrim(track_id) <> '')
);

-- ---------------------------------------------------------------------------
-- Global two-level backline catalog
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tbl_backline_category (
    id uuid NOT NULL,
    parent_id uuid,
    code varchar(96) NOT NULL,
    name varchar(160) NOT NULL,
    normalized_name varchar(160) NOT NULL,
    icon_key varchar(128),
    level smallint NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_backline_category PRIMARY KEY (id),
    CONSTRAINT fk_backline_category_parent
        FOREIGN KEY (parent_id)
        REFERENCES tbl_backline_category (id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_backline_category_code UNIQUE (code),
    CONSTRAINT uk_backline_category_parent_normalized
        UNIQUE (parent_id, normalized_name),
    CONSTRAINT ck_backline_category_level CHECK (level IN (0, 1)),
    CONSTRAINT ck_backline_category_shape CHECK (
        (level = 0 AND parent_id IS NULL)
        OR (level = 1 AND parent_id IS NOT NULL)
    ),
    CONSTRAINT ck_backline_category_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_backline_category_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_backline_category_normalized_name_not_blank
        CHECK (btrim(normalized_name) <> ''),
    CONSTRAINT ck_backline_category_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_backline_category_version CHECK (version >= 0)
);

-- Hibernate-created local schemas contain the same non-null version column but
-- do not assign a database default. Seed statements must work against both the
-- canonical migration shape and that local-development shape.
ALTER TABLE tbl_backline_category
    ALTER COLUMN version SET DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS uk_backline_root_normalized_name
    ON tbl_backline_category (normalized_name)
    WHERE parent_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_backline_category_parent_active
    ON tbl_backline_category (parent_id, active, sort_order);

CREATE INDEX IF NOT EXISTS idx_backline_category_normalized
    ON tbl_backline_category (normalized_name);

CREATE OR REPLACE FUNCTION soundconnect_validate_backline_category_parent()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_level smallint;
BEGIN
    IF NEW.parent_id = NEW.id THEN
        RAISE EXCEPTION 'backline category cannot be its own parent'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_two_levels';
    END IF;

    IF (NEW.parent_id IS NOT NULL OR NEW.level <> 0)
       AND EXISTS (
           SELECT 1 FROM tbl_backline_category child WHERE child.parent_id = NEW.id
       ) THEN
        RAISE EXCEPTION 'a category with children must remain a root category'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_two_levels';
    END IF;

    IF NEW.parent_id IS NULL THEN
        IF NEW.level <> 0 THEN
            RAISE EXCEPTION 'root backline category must have level 0'
                USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_shape';
        END IF;
        RETURN NEW;
    END IF;

    SELECT level INTO parent_level
      FROM tbl_backline_category
     WHERE id = NEW.parent_id;

    IF parent_level IS NULL OR parent_level <> 0 OR NEW.level <> 1 THEN
        RAISE EXCEPTION 'backline catalog supports exactly two levels'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_two_levels';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_backline_category_parent ON tbl_backline_category;
CREATE TRIGGER trg_backline_category_parent
BEFORE INSERT OR UPDATE OF parent_id, level ON tbl_backline_category
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_backline_category_parent();

-- Seed normalization must not depend on the database cluster locale. This is
-- the SQL equivalent of BacklineCategoryNames: all Turkish I variants share
-- one ASCII-i uniqueness key, while the remaining Turkish uppercase letters
-- are lowered explicitly under the built-in C collation.
CREATE OR REPLACE FUNCTION soundconnect_normalize_backline_name(raw_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT btrim(lower(
        translate(raw_name, 'İıÇĞÖŞÜ', 'Iiçğöşü') COLLATE "C"
    ));
$$;

-- Canonical reference catalog from backline-category-seed.json. A local
-- Hibernate bootstrap may have inserted these rows with generated UUIDs before
-- this migration runs. Adopt an existing root by code or normalized name so
-- its identity and every external reference remain untouched. Unrelated
-- administrator-created categories are neither updated nor removed.
WITH seed(id, code, name, icon_key, sort_order) AS (
    VALUES
    ('10000000-0000-0000-0000-000000000001'::uuid, 'drums-cymbals', 'Davul, Bateri & Zil', 'drum-kit', 0),
    ('10000000-0000-0000-0000-000000000002'::uuid, 'guitar-amplifiers', 'Gitar Amfileri', 'guitar-amps', 1),
    ('10000000-0000-0000-0000-000000000003'::uuid, 'bass-amplifiers', 'Bas Gitar Amfileri', 'bass-amps', 2),
    ('10000000-0000-0000-0000-000000000004'::uuid, 'piano-keyboards-synths', 'Piyano, Klavye & Synth', 'keyboards', 3),
    ('10000000-0000-0000-0000-000000000005'::uuid, 'percussion', 'Perküsyon', 'percussion', 4),
    ('10000000-0000-0000-0000-000000000006'::uuid, 'guitars-basses', 'Gitarlar & Baslar', 'guitars-basses', 5),
    ('10000000-0000-0000-0000-000000000007'::uuid, 'orchestral-instruments', 'Yaylılar & Orkestra Enstrümanları', 'orchestral-strings', 6),
    ('10000000-0000-0000-0000-000000000008'::uuid, 'dj-equipment', 'DJ Ekipmanları', 'dj', 7),
    ('10000000-0000-0000-0000-000000000009'::uuid, 'pro-audio-studio', 'Pro Audio & Stüdyo', 'pro-audio-studio', 8),
    ('10000000-0000-0000-0000-000000000010'::uuid, 'stage-backline-accessories', 'Sahne & Backline Aksesuarları', 'backline-accessories', 9)
)
INSERT INTO tbl_backline_category
    (id, parent_id, code, name, normalized_name, icon_key, level, sort_order, active)
SELECT seed.id,
       NULL,
       seed.code,
       seed.name,
       soundconnect_normalize_backline_name(seed.name),
       seed.icon_key,
       0,
       seed.sort_order,
       true
  FROM seed
 WHERE NOT EXISTS (
           SELECT 1
             FROM tbl_backline_category existing
            WHERE existing.code = seed.code
       )
   AND NOT EXISTS (
           SELECT 1
             FROM tbl_backline_category existing
            WHERE existing.parent_id IS NULL
              AND existing.normalized_name = soundconnect_normalize_backline_name(seed.name)
       )
ON CONFLICT DO NOTHING;

-- Stable leaf IDs are used only for a genuinely missing canonical row. An
-- existing JSON-seeded leaf is adopted by code or by normalized name under its
-- resolved root; no category is moved, renamed, re-keyed, or reactivated.
WITH seed(parent_code, parent_name, id, code, name, sort_order) AS (
    VALUES
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000001'::uuid, 'acoustic-drum-sets', 'Davul / Bateri - Akustik Setler', 0),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000002'::uuid, 'electronic-drum-sets', 'Davul / Bateri - Elektronik Setler', 1),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000074'::uuid, 'drum-shells-individual-drums', 'Davul Gövdeleri & Tekil Davullar', 2),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000003'::uuid, 'snare-drums', 'Trampetler (Snare)', 3),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000004'::uuid, 'cymbals', 'Ziller', 4),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000005'::uuid, 'drum-pedals', 'Davul Aksesuarları - Pedallar', 5),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000006'::uuid, 'electronic-drum-pads-modules', 'Davul Aksesuarları - Elektronik Padler & Modüller', 6),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000007'::uuid, 'drum-hardware-stands', 'Davul Aksesuarları - Hardware & Standlar', 7),
    ('drums-cymbals', 'Davul, Bateri & Zil', '20000000-0000-0000-0000-000000000008'::uuid, 'drum-spares-consumables', 'Davul Yedek Parçaları & Teknik Aksesuarları', 8),

    ('guitar-amplifiers', 'Gitar Amfileri', '20000000-0000-0000-0000-000000000009'::uuid, 'electric-guitar-combo-amps', 'Elektrik Gitar Amfileri - Combo', 0),
    ('guitar-amplifiers', 'Gitar Amfileri', '20000000-0000-0000-0000-000000000010'::uuid, 'electric-guitar-amp-heads', 'Elektrik Gitar Amfileri - Kafa', 1),
    ('guitar-amplifiers', 'Gitar Amfileri', '20000000-0000-0000-0000-000000000011'::uuid, 'electric-guitar-cabinets', 'Kabinler - Elektrik Gitar', 2),
    ('guitar-amplifiers', 'Gitar Amfileri', '20000000-0000-0000-0000-000000000012'::uuid, 'acoustic-guitar-amps', 'Akustik Gitar Amfileri', 3),

    ('bass-amplifiers', 'Bas Gitar Amfileri', '20000000-0000-0000-0000-000000000015'::uuid, 'bass-combo-amps', 'Bas Combo Amfileri', 0),
    ('bass-amplifiers', 'Bas Gitar Amfileri', '20000000-0000-0000-0000-000000000016'::uuid, 'bass-amp-heads', 'Bas Amfi Kafaları', 1),
    ('bass-amplifiers', 'Bas Gitar Amfileri', '20000000-0000-0000-0000-000000000017'::uuid, 'bass-cabinets', 'Bas Kabinleri', 2),
    ('bass-amplifiers', 'Bas Gitar Amfileri', '20000000-0000-0000-0000-000000000018'::uuid, 'bass-preamp-di-effects', 'Bas Preamp, DI & Efektler', 3),

    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000019'::uuid, 'acoustic-pianos', 'Akustik Piyanolar', 0),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000020'::uuid, 'digital-stage-pianos', 'Dijital & Sahne Piyanoları', 1),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000021'::uuid, 'keyboards-workstations', 'Keyboard & Workstationlar', 2),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000022'::uuid, 'synthesizers', 'Synthesizerlar', 3),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000023'::uuid, 'organs', 'Orglar', 4),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000024'::uuid, 'electromechanical-pianos', 'Elektromekanik Piyanolar (Rhodes vb.)', 5),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000025'::uuid, 'midi-keyboards-controllers', 'MIDI Klavyeler & Controllerlar', 6),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000026'::uuid, 'keyboard-amplifiers', 'Klavye Amfileri', 7),
    ('piano-keyboards-synths', 'Piyano, Klavye & Synth', '20000000-0000-0000-0000-000000000027'::uuid, 'keyboard-stands-pedals-benches', 'Klavye Standları, Pedallar & Tabureler', 8),

    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000028'::uuid, 'congas-tumbas-quintos', 'Conga, Tumba & Quinto', 0),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000029'::uuid, 'bongos', 'Bongo', 1),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000030'::uuid, 'timbales', 'Timbales', 2),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000031'::uuid, 'djembes', 'Djembe', 3),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000032'::uuid, 'cajons', 'Cajon', 4),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000033'::uuid, 'traditional-turkish-percussion', 'Darbuka, Bendir, Tef & Asma Davul', 5),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000034'::uuid, 'world-percussion', 'Udu, Shekere & Dünya Perküsyonları', 6),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000035'::uuid, 'small-hand-percussion', 'Shaker, Marakas, Cabasa & Küçük Perküsyonlar', 7),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000036'::uuid, 'effect-percussion', 'Jam Block, Cowbell, Chimes & Efekt Perküsyonları', 8),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000075'::uuid, 'mallet-percussion', 'Mallet Perküsyonları - Marimba, Vibrafon & Ksilofon', 9),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000076'::uuid, 'orchestral-percussion', 'Orkestra Perküsyonları - Timpani & Konser Davulları', 10),
    ('percussion', 'Perküsyon', '20000000-0000-0000-0000-000000000037'::uuid, 'percussion-stands-accessories', 'Perküsyon Masaları, Standları & Aksesuarları', 11),

    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000038'::uuid, 'electric-guitars', 'Elektro Gitarlar', 0),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000039'::uuid, 'acoustic-classical-guitars', 'Akustik & Klasik Gitarlar', 1),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000040'::uuid, 'electric-bass-guitars', 'Elektro Bas Gitarlar', 2),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000041'::uuid, 'acoustic-bass-guitars', 'Akustik Bas Gitarlar', 3),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000042'::uuid, 'double-basses', 'Kontrbaslar', 4),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000043'::uuid, 'guitar-bass-accessories', 'Gitar & Bas Aksesuarları', 5),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000013'::uuid, 'guitar-modelers-multi-effects', 'Modelleyiciler & Multi-Efektler', 6),
    ('guitars-basses', 'Gitarlar & Baslar', '20000000-0000-0000-0000-000000000014'::uuid, 'guitar-pedals-footswitches', 'Gitar Pedalları & Footswitchler', 7),

    ('orchestral-instruments', 'Yaylılar & Orkestra Enstrümanları', '20000000-0000-0000-0000-000000000044'::uuid, 'string-instruments', 'Yaylı Enstrümanlar', 0),
    ('orchestral-instruments', 'Yaylılar & Orkestra Enstrümanları', '20000000-0000-0000-0000-000000000045'::uuid, 'woodwind-instruments', 'Tahta Nefesli Enstrümanlar', 1),
    ('orchestral-instruments', 'Yaylılar & Orkestra Enstrümanları', '20000000-0000-0000-0000-000000000046'::uuid, 'brass-instruments', 'Bakır Üflemeli Enstrümanlar', 2),
    ('orchestral-instruments', 'Yaylılar & Orkestra Enstrümanları', '20000000-0000-0000-0000-000000000047'::uuid, 'folk-world-instruments', 'Halk & Dünya Enstrümanları', 3),
    ('orchestral-instruments', 'Yaylılar & Orkestra Enstrümanları', '20000000-0000-0000-0000-000000000048'::uuid, 'orchestra-accessories', 'Orkestra Aksesuarları', 4),

    ('dj-equipment', 'DJ Ekipmanları', '20000000-0000-0000-0000-000000000049'::uuid, 'cdj-media-players', 'CDJ & Medya Oynatıcılar', 0),
    ('dj-equipment', 'DJ Ekipmanları', '20000000-0000-0000-0000-000000000050'::uuid, 'turntables', 'Turntablelar', 1),
    ('dj-equipment', 'DJ Ekipmanları', '20000000-0000-0000-0000-000000000051'::uuid, 'dj-mixers', 'DJ Mikserleri', 2),
    ('dj-equipment', 'DJ Ekipmanları', '20000000-0000-0000-0000-000000000052'::uuid, 'dj-controllers', 'DJ Controllerlar', 3),
    ('dj-equipment', 'DJ Ekipmanları', '20000000-0000-0000-0000-000000000053'::uuid, 'samplers-drum-machines', 'Sampler & Drum Machine', 4),
    ('dj-equipment', 'DJ Ekipmanları', '20000000-0000-0000-0000-000000000054'::uuid, 'dj-monitors-accessories', 'DJ Monitörleri & Aksesuarları', 5),

    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000055'::uuid, 'dynamic-microphones', 'Dinamik Mikrofonlar', 0),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000056'::uuid, 'condenser-ribbon-microphones', 'Kondansatör & Ribbon Mikrofonlar', 1),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000057'::uuid, 'wireless-microphone-systems', 'Kablosuz Mikrofon Sistemleri', 2),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000077'::uuid, 'instrument-wireless-systems', 'Enstrüman Kablosuz Sistemleri', 3),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000058'::uuid, 'analog-digital-mixers', 'Analog & Dijital Mikserler', 4),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000059'::uuid, 'pa-speakers-subwoofers', 'PA Hoparlörleri & Subwooferlar', 5),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000060'::uuid, 'stage-monitors', 'Sahne Monitörleri', 6),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000061'::uuid, 'in-ear-monitor-systems', 'In-Ear Monitor Sistemleri', 7),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000062'::uuid, 'di-boxes-reamp-boxes', 'DI Box & Reamp Kutuları', 8),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000063'::uuid, 'audio-interfaces-recorders', 'Ses Kartları & Kayıt Cihazları', 9),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000078'::uuid, 'headphones-cue-distribution', 'Kulaklıklar & Kulaklık Dağıtım Sistemleri', 10),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000064'::uuid, 'studio-monitors', 'Stüdyo Monitörleri', 11),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000065'::uuid, 'outboard-preamps-processors', 'Outboard, Preamp & Sinyal İşlemciler', 12),
    ('pro-audio-studio', 'Pro Audio & Stüdyo', '20000000-0000-0000-0000-000000000079'::uuid, 'power-amplifiers-system-processors', 'Güç Amplifikatörleri & PA Sistem İşlemcileri', 13),

    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000066'::uuid, 'instrument-microphone-speaker-stands', 'Enstrüman, Mikrofon & Hoparlör Standları', 0),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000067'::uuid, 'music-stands', 'Nota Sehpaları', 1),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000068'::uuid, 'drum-thrones-piano-benches', 'Davul Tabureleri & Piyano Bankları', 2),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000069'::uuid, 'cables-multicores-adapters', 'Kablolar, Multicorelar & Adaptörler', 3),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000070'::uuid, 'power-distribution-regulators-transformers', 'Güç Dağıtımı, Regülatörler & Trafolar', 4),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000071'::uuid, 'racks-cases-transport', 'Rack, Case & Taşıma Çözümleri', 5),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000072'::uuid, 'risers-stage-platforms', 'Riser & Sahne Platformları', 6),
    ('stage-backline-accessories', 'Sahne & Backline Aksesuarları', '20000000-0000-0000-0000-000000000073'::uuid, 'consumables-spare-parts', 'Yedek Parçalar & Teknik Aksesuarlar', 7)
)
INSERT INTO tbl_backline_category
    (id, parent_id, code, name, normalized_name, level, sort_order, active)
SELECT seed.id,
       parent.id,
       seed.code,
       seed.name,
       soundconnect_normalize_backline_name(seed.name),
       1,
       seed.sort_order,
       true
  FROM seed
  JOIN LATERAL (
       SELECT candidate.id
         FROM tbl_backline_category candidate
        WHERE candidate.parent_id IS NULL
          AND (
              candidate.code = seed.parent_code
              OR candidate.normalized_name = soundconnect_normalize_backline_name(seed.parent_name)
          )
        ORDER BY CASE WHEN candidate.code = seed.parent_code THEN 0 ELSE 1 END,
                 candidate.id
        LIMIT 1
  ) parent ON true
 WHERE NOT EXISTS (
           SELECT 1
             FROM tbl_backline_category existing
            WHERE existing.code = seed.code
       )
   AND NOT EXISTS (
           SELECT 1
             FROM tbl_backline_category existing
            WHERE existing.parent_id = parent.id
              AND existing.normalized_name = soundconnect_normalize_backline_name(seed.name)
       )
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Rooms, ordered attachments, reservation requests and exclusive occupancy
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tbl_studio_room (
    id uuid NOT NULL,
    studio_profile_id uuid NOT NULL,
    client_request_id uuid NOT NULL,
    creation_payload_hash varchar(64) NOT NULL,
    slot_index integer NOT NULL,
    name varchar(100) NOT NULL,
    short_description varchar(60),
    capacity integer NOT NULL,
    minimum_capacity integer,
    hourly_price_minor bigint,
    currency varchar(3) NOT NULL DEFAULT 'TRY',
    reservation_approval_required boolean NOT NULL DEFAULT true,
    pending_reservation_approval_required boolean,
    reservation_approval_policy_effective_at timestamp with time zone,
    archived_at timestamp with time zone,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_room PRIMARY KEY (id),
    CONSTRAINT fk_studio_room_profile
        FOREIGN KEY (studio_profile_id)
        REFERENCES tbl_studio_profile (id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_studio_room_profile_client_request
        UNIQUE (studio_profile_id, client_request_id),
    CONSTRAINT ck_studio_room_creation_payload_hash
        CHECK (creation_payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_studio_room_slot CHECK (slot_index BETWEEN 0 AND 9),
    CONSTRAINT ck_studio_room_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_studio_room_capacity CHECK (capacity BETWEEN 1 AND 100),
    CONSTRAINT ck_studio_room_minimum_capacity CHECK (
        minimum_capacity IS NULL
        OR minimum_capacity BETWEEN 1 AND capacity
    ),
    CONSTRAINT ck_studio_room_approval_policy_schedule CHECK (
        (pending_reservation_approval_required IS NULL
            AND reservation_approval_policy_effective_at IS NULL)
        OR
        (pending_reservation_approval_required IS NOT NULL
            AND reservation_approval_policy_effective_at IS NOT NULL)
    ),
    CONSTRAINT ck_studio_room_price CHECK (
        hourly_price_minor IS NULL OR hourly_price_minor BETWEEN 1 AND 100000000
    ),
    CONSTRAINT ck_studio_room_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_studio_room_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_studio_room_active_slot
    ON tbl_studio_room (studio_profile_id, slot_index)
    WHERE archived_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_studio_room_owner_list
    ON tbl_studio_room (studio_profile_id, archived_at, slot_index, id);

CREATE TABLE IF NOT EXISTS tbl_studio_room_feature (
    id uuid NOT NULL,
    room_id uuid NOT NULL,
    label varchar(60) NOT NULL,
    order_index integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_room_feature PRIMARY KEY (id),
    CONSTRAINT fk_studio_room_feature_room
        FOREIGN KEY (room_id)
        REFERENCES tbl_studio_room (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_studio_room_feature_order UNIQUE (room_id, order_index),
    CONSTRAINT uk_studio_room_feature_label UNIQUE (room_id, label),
    CONSTRAINT ck_studio_room_feature_order CHECK (order_index BETWEEN 0 AND 7),
    CONSTRAINT ck_studio_room_feature_label_not_blank CHECK (btrim(label) <> '')
);

CREATE TABLE IF NOT EXISTS tbl_studio_room_photo (
    id uuid NOT NULL,
    room_id uuid NOT NULL,
    media_asset_id uuid NOT NULL,
    order_index integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_room_photo PRIMARY KEY (id),
    CONSTRAINT fk_studio_room_photo_room
        FOREIGN KEY (room_id)
        REFERENCES tbl_studio_room (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_studio_room_photo_media
        FOREIGN KEY (media_asset_id)
        REFERENCES tbl_media_asset (id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_studio_room_photo_order UNIQUE (room_id, order_index),
    CONSTRAINT uk_studio_room_photo_asset UNIQUE (room_id, media_asset_id),
    CONSTRAINT ck_studio_room_photo_order CHECK (order_index BETWEEN 0 AND 9)
);

CREATE INDEX IF NOT EXISTS idx_studio_room_photo_media
    ON tbl_studio_room_photo (media_asset_id);

CREATE TABLE IF NOT EXISTS tbl_studio_room_reservation (
    id uuid NOT NULL,
    room_id uuid NOT NULL,
    requester_id uuid NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    status varchar(32) NOT NULL,
    approval_required_snapshot boolean NOT NULL,
    hourly_price_minor_snapshot bigint,
    total_price_minor_snapshot bigint,
    currency_snapshot varchar(3) NOT NULL,
    contact_phone_snapshot varchar(16),
    client_request_id uuid NOT NULL,
    decided_at timestamp with time zone,
    decided_by uuid,
    cancelled_at timestamp with time zone,
    cancelled_by uuid,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_room_reservation PRIMARY KEY (id),
    CONSTRAINT fk_studio_room_reservation_room
        FOREIGN KEY (room_id) REFERENCES tbl_studio_room (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_room_reservation_requester
        FOREIGN KEY (requester_id) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_room_reservation_decider
        FOREIGN KEY (decided_by) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_room_reservation_canceller
        FOREIGN KEY (cancelled_by) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT uk_studio_room_reservation_client_request
        UNIQUE (requester_id, client_request_id),
    CONSTRAINT ck_studio_room_reservation_range CHECK (starts_at < ends_at),
    CONSTRAINT ck_studio_room_reservation_duration CHECK (
        extract(epoch FROM (ends_at - starts_at)) BETWEEN 3600 AND 14400
        AND mod(extract(epoch FROM (ends_at - starts_at)), 3600) = 0
    ),
    CONSTRAINT ck_studio_room_reservation_status CHECK (status IN (
        'PENDING_APPROVAL', 'CONFIRMED', 'REJECTED_BY_STUDIO',
        'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_STUDIO', 'EXPIRED'
    )),
    CONSTRAINT ck_studio_room_reservation_price CHECK (
        hourly_price_minor_snapshot IS NULL
        OR hourly_price_minor_snapshot BETWEEN 1 AND 100000000
    ),
    CONSTRAINT ck_studio_room_reservation_total_price CHECK (
        total_price_minor_snapshot IS NULL
        OR total_price_minor_snapshot BETWEEN 1 AND 400000000
    ),
    CONSTRAINT ck_studio_room_reservation_pricing_snapshot CHECK (
        (hourly_price_minor_snapshot IS NULL AND total_price_minor_snapshot IS NULL)
        OR (
            hourly_price_minor_snapshot IS NOT NULL
            AND total_price_minor_snapshot = hourly_price_minor_snapshot
                * (extract(epoch FROM (ends_at - starts_at))::bigint / 3600)
        )
    ),
    CONSTRAINT ck_studio_room_reservation_currency CHECK (
        currency_snapshot ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT ck_studio_room_reservation_state_shape CHECK (
        (decided_at IS NULL) = (decided_by IS NULL)
        AND (cancelled_at IS NULL) = (cancelled_by IS NULL)
        AND (status <> 'PENDING_APPROVAL' OR (
            approval_required_snapshot AND decided_at IS NULL AND cancelled_at IS NULL
        ))
        AND (status <> 'CONFIRMED' OR cancelled_at IS NULL)
        AND (status <> 'REJECTED_BY_STUDIO' OR (
            decided_at IS NOT NULL AND cancelled_at IS NULL
        ))
        AND (status NOT IN ('CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_STUDIO')
            OR cancelled_at IS NOT NULL)
    ),
    CONSTRAINT ck_studio_room_reservation_version CHECK (version >= 0),
    CONSTRAINT ex_studio_room_reservation_requester_overlap
        EXCLUDE USING gist (
            requester_id WITH =,
            room_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        ) WHERE (status IN ('PENDING_APPROVAL', 'CONFIRMED'))
);

CREATE INDEX IF NOT EXISTS idx_studio_room_reservation_schedule
    ON tbl_studio_room_reservation (room_id, status, starts_at, id);

CREATE INDEX IF NOT EXISTS idx_studio_room_reservation_requester
    ON tbl_studio_room_reservation (requester_id, status, starts_at DESC, id);

-- Schedule and customer-history reads do not always filter by status. Keep
-- matching indexes so PostgreSQL can range/ordered-scan instead of sorting a
-- Studio's or requester's complete reservation history.
CREATE INDEX IF NOT EXISTS idx_studio_room_reservation_room_time
    ON tbl_studio_room_reservation (room_id, starts_at, id);

CREATE INDEX IF NOT EXISTS idx_studio_room_reservation_requester_time
    ON tbl_studio_room_reservation (requester_id, starts_at DESC, id);

-- Do not round fractional seconds before checking the whole-hour contract.
-- Recreate this constraint on reruns so release-candidate schemas with the
-- earlier bigint cast are repaired as well.
ALTER TABLE tbl_studio_room_reservation
    DROP CONSTRAINT IF EXISTS ck_studio_room_reservation_duration;
ALTER TABLE tbl_studio_room_reservation
    ADD CONSTRAINT ck_studio_room_reservation_duration CHECK (
        extract(epoch FROM (ends_at - starts_at)) BETWEEN 3600 AND 14400
        AND mod(extract(epoch FROM (ends_at - starts_at)), 3600) = 0
    );

-- Different customers may submit overlapping approval requests, but one
-- customer cannot spam the same room/time with fresh idempotency keys. The
-- application opportunistically materializes already-started pending requests
-- as EXPIRED before inserting a new request.
UPDATE tbl_studio_room_reservation
   SET status = 'EXPIRED',
       updated_at = CURRENT_TIMESTAMP,
       version = version + 1
 WHERE status = 'PENDING_APPROVAL'
   AND starts_at <= CURRENT_TIMESTAMP;

-- A database upgraded from a build predating the requester-overlap invariant
-- may already contain duplicate future requests. Preserve every confirmed
-- booking and greedily retain pending candidates in original creation order.
-- Each candidate is compared only with pending rows that actually survived;
-- this matters for an A--B--C interval chain where A and C do not overlap:
-- B is expired while both A and C remain pending. A simple self-join against
-- every earlier row would incorrectly expire C merely because it overlaps B.
--
-- Pending rows that overlap a confirmed booking are always retired. Multiple
-- conflicting confirmed rows are intentionally not rewritten: that indicates
-- corrupt booking data requiring an operator decision, and constraint
-- installation will fail loudly instead of silently cancelling a customer.
-- The repair is skipped entirely once the invariant exists, keeping later
-- migration reruns bounded to the cheap started-pending lifecycle update.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'tbl_studio_room_reservation'::regclass
           AND conname = 'ex_studio_room_reservation_requester_overlap'
    ) THEN
WITH RECURSIVE pending_candidates AS (
    SELECT reservation.id,
           reservation.requester_id,
           reservation.room_id,
           tstzrange(reservation.starts_at, reservation.ends_at, '[)') AS booking_range,
           row_number() OVER (
               PARTITION BY reservation.requester_id, reservation.room_id
               ORDER BY reservation.created_at, reservation.id
           ) AS sequence_number
      FROM tbl_studio_room_reservation reservation
     WHERE reservation.status = 'PENDING_APPROVAL'
       AND NOT EXISTS (
           SELECT 1
             FROM tbl_studio_room_reservation confirmed
            WHERE confirmed.requester_id = reservation.requester_id
              AND confirmed.room_id = reservation.room_id
              AND confirmed.status = 'CONFIRMED'
              AND tstzrange(confirmed.starts_at, confirmed.ends_at, '[)')
                  && tstzrange(reservation.starts_at, reservation.ends_at, '[)')
       )
), survivor_walk AS (
    SELECT candidate.id,
           candidate.requester_id,
           candidate.room_id,
           candidate.sequence_number,
           ARRAY[candidate.booking_range] AS kept_ranges,
           true AS keep_candidate
      FROM pending_candidates candidate
     WHERE candidate.sequence_number = 1

    UNION ALL

    SELECT candidate.id,
           candidate.requester_id,
           candidate.room_id,
           candidate.sequence_number,
           CASE
               WHEN candidate.booking_range && ANY (walk.kept_ranges)
                   THEN walk.kept_ranges
               ELSE array_append(walk.kept_ranges, candidate.booking_range)
           END AS kept_ranges,
           NOT (candidate.booking_range && ANY (walk.kept_ranges)) AS keep_candidate
      FROM survivor_walk walk
      JOIN pending_candidates candidate
        ON candidate.requester_id = walk.requester_id
       AND candidate.room_id = walk.room_id
       AND candidate.sequence_number = walk.sequence_number + 1
), pending_to_expire AS (
    SELECT reservation.id
      FROM tbl_studio_room_reservation reservation
     WHERE reservation.status = 'PENDING_APPROVAL'
       AND (
           EXISTS (
               SELECT 1
                 FROM tbl_studio_room_reservation confirmed
                WHERE confirmed.requester_id = reservation.requester_id
                  AND confirmed.room_id = reservation.room_id
                  AND confirmed.status = 'CONFIRMED'
                  AND tstzrange(confirmed.starts_at, confirmed.ends_at, '[)')
                      && tstzrange(reservation.starts_at, reservation.ends_at, '[)')
           )
           OR EXISTS (
               SELECT 1
                 FROM survivor_walk walk
                WHERE walk.id = reservation.id
                  AND NOT walk.keep_candidate
           )
       )
)
UPDATE tbl_studio_room_reservation reservation
   SET status = 'EXPIRED',
       updated_at = CURRENT_TIMESTAMP,
       version = reservation.version + 1
  FROM pending_to_expire expired
 WHERE reservation.id = expired.id;

        ALTER TABLE tbl_studio_room_reservation
            ADD CONSTRAINT ex_studio_room_reservation_requester_overlap
            EXCLUDE USING gist (
                requester_id WITH =,
                room_id WITH =,
                tstzrange(starts_at, ends_at, '[)') WITH &&
            ) WHERE (status IN ('PENDING_APPROVAL', 'CONFIRMED'));
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS tbl_studio_room_occupancy (
    id uuid NOT NULL,
    room_id uuid NOT NULL,
    reservation_id uuid,
    client_request_id uuid,
    type varchar(24) NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_by uuid NOT NULL,
    released_at timestamp with time zone,
    released_by uuid,
    release_reason varchar(200),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_room_occupancy PRIMARY KEY (id),
    CONSTRAINT fk_studio_room_occupancy_room
        FOREIGN KEY (room_id) REFERENCES tbl_studio_room (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_room_occupancy_reservation
        FOREIGN KEY (reservation_id) REFERENCES tbl_studio_room_reservation (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_room_occupancy_creator
        FOREIGN KEY (created_by) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_room_occupancy_releaser
        FOREIGN KEY (released_by) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT uk_studio_room_occupancy_reservation UNIQUE (reservation_id),
    CONSTRAINT ck_studio_room_occupancy_type CHECK (type IN ('RESERVATION', 'MANUAL_BLOCK')),
    CONSTRAINT ck_studio_room_occupancy_shape CHECK (
        (type = 'RESERVATION' AND reservation_id IS NOT NULL AND client_request_id IS NULL)
        OR (type = 'MANUAL_BLOCK' AND reservation_id IS NULL AND client_request_id IS NOT NULL)
    ),
    CONSTRAINT ck_studio_room_occupancy_range CHECK (starts_at < ends_at),
    CONSTRAINT ck_studio_room_occupancy_duration CHECK (
        mod(extract(epoch FROM (ends_at - starts_at)), 3600) = 0
        AND (
            (type = 'RESERVATION'
                AND extract(epoch FROM (ends_at - starts_at)) BETWEEN 3600 AND 14400)
            OR
            (type = 'MANUAL_BLOCK'
                AND extract(epoch FROM (ends_at - starts_at)) BETWEEN 3600 AND 50400)
        )
    ),
    CONSTRAINT ck_studio_room_occupancy_release CHECK (
        (active AND released_at IS NULL AND released_by IS NULL)
        OR (NOT active AND released_at IS NOT NULL AND released_by IS NOT NULL)
    ),
    CONSTRAINT ck_studio_room_occupancy_version CHECK (version >= 0),
    CONSTRAINT ex_studio_room_occupancy_no_overlap
        EXCLUDE USING gist (
            room_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        ) WHERE (active)
);

-- Hibernate may have created the table before this migration was introduced.
-- CREATE TABLE IF NOT EXISTS does not backfill constraints on such a table, so
-- install the database-level room-overlap invariant explicitly on every legacy
-- schema. Existing conflicting active rows are intentionally not rewritten:
-- constraint installation must fail closed and require an operator decision.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'tbl_studio_room_occupancy'::regclass
           AND conname = 'ex_studio_room_occupancy_no_overlap'
    ) THEN
        ALTER TABLE tbl_studio_room_occupancy
            ADD CONSTRAINT ex_studio_room_occupancy_no_overlap
            EXCLUDE USING gist (
                room_id WITH =,
                tstzrange(starts_at, ends_at, '[)') WITH &&
            ) WHERE (active);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_studio_room_occupancy_schedule
    ON tbl_studio_room_occupancy (room_id, active, starts_at, id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_studio_occupancy_manual_client_request
    ON tbl_studio_room_occupancy (created_by, client_request_id)
    WHERE client_request_id IS NOT NULL;

-- Earlier release candidates applied the customer reservation limit (four
-- hours) to every occupancy kind. Owner-created blocks intentionally cover up
-- to the complete 09:00..23:00 operating day, so repair that constraint on a
-- rerun while preserving the stricter reservation limit.
ALTER TABLE tbl_studio_room_occupancy
    DROP CONSTRAINT IF EXISTS ck_studio_room_occupancy_duration;
ALTER TABLE tbl_studio_room_occupancy
    ADD CONSTRAINT ck_studio_room_occupancy_duration CHECK (
        mod(extract(epoch FROM (ends_at - starts_at)), 3600) = 0
        AND (
            (type = 'RESERVATION'
                AND extract(epoch FROM (ends_at - starts_at)) BETWEEN 3600 AND 14400)
            OR
            (type = 'MANUAL_BLOCK'
                AND extract(epoch FROM (ends_at - starts_at)) BETWEEN 3600 AND 50400)
        )
    );

CREATE OR REPLACE FUNCTION soundconnect_validate_reservation_occupancy()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    reservation_room uuid;
    reservation_status varchar(32);
    reservation_starts_at timestamp with time zone;
    reservation_ends_at timestamp with time zone;
BEGIN
    IF NEW.type = 'MANUAL_BLOCK' THEN
        RETURN NEW;
    END IF;

    SELECT room_id, status, starts_at, ends_at
      INTO reservation_room, reservation_status,
           reservation_starts_at, reservation_ends_at
      FROM tbl_studio_room_reservation
     WHERE id = NEW.reservation_id;

    IF reservation_room IS NULL
       OR reservation_room <> NEW.room_id
       OR reservation_status <> 'CONFIRMED'
       OR reservation_starts_at <> NEW.starts_at
       OR reservation_ends_at <> NEW.ends_at THEN
        RAISE EXCEPTION 'reservation occupancy must match a confirmed reservation in the same room and time window'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_studio_room_occupancy_reservation_match';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_studio_room_occupancy_reservation
    ON tbl_studio_room_occupancy;
CREATE TRIGGER trg_studio_room_occupancy_reservation
BEFORE INSERT OR UPDATE OF room_id, reservation_id, type, starts_at, ends_at
ON tbl_studio_room_occupancy
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_reservation_occupancy();

-- ---------------------------------------------------------------------------
-- Equipment inventory, ordered attachments and daily availability projection
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tbl_studio_equipment (
    id uuid NOT NULL,
    studio_profile_id uuid NOT NULL,
    creation_client_request_id uuid NOT NULL,
    creation_payload_hash varchar(64) NOT NULL,
    category_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    brand varchar(60),
    model varchar(60),
    description varchar(300),
    total_quantity integer NOT NULL,
    archived_at timestamp with time zone,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_equipment PRIMARY KEY (id),
    CONSTRAINT fk_studio_equipment_profile
        FOREIGN KEY (studio_profile_id) REFERENCES tbl_studio_profile (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_equipment_category
        FOREIGN KEY (category_id) REFERENCES tbl_backline_category (id) ON DELETE RESTRICT,
    CONSTRAINT uk_studio_equipment_create_request
        UNIQUE (studio_profile_id, creation_client_request_id),
    CONSTRAINT ck_studio_equipment_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_studio_equipment_creation_payload_hash
        CHECK (creation_payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_studio_equipment_total_quantity CHECK (total_quantity BETWEEN 1 AND 999),
    CONSTRAINT ck_studio_equipment_version CHECK (version >= 0)
);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_studio_active
    ON tbl_studio_equipment (studio_profile_id, archived_at);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_category
    ON tbl_studio_equipment (category_id);

CREATE OR REPLACE FUNCTION soundconnect_validate_studio_equipment_category()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    category_level smallint;
    category_active boolean;
BEGIN
    SELECT level, active INTO category_level, category_active
      FROM tbl_backline_category
     WHERE id = NEW.category_id;

    IF category_level IS NULL OR category_level <> 1 OR NOT category_active THEN
        RAISE EXCEPTION 'studio equipment must reference an active leaf category'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_studio_equipment_leaf_category';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_studio_equipment_category ON tbl_studio_equipment;
CREATE TRIGGER trg_studio_equipment_category
BEFORE INSERT OR UPDATE OF category_id ON tbl_studio_equipment
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_studio_equipment_category();

CREATE TABLE IF NOT EXISTS tbl_studio_equipment_feature (
    id uuid NOT NULL,
    equipment_id uuid NOT NULL,
    position integer NOT NULL,
    label varchar(60) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_equipment_feature PRIMARY KEY (id),
    CONSTRAINT fk_studio_equipment_feature_equipment
        FOREIGN KEY (equipment_id) REFERENCES tbl_studio_equipment (id) ON DELETE CASCADE,
    CONSTRAINT uk_studio_equipment_feature_position UNIQUE (equipment_id, position),
    CONSTRAINT uk_studio_equipment_feature_label UNIQUE (equipment_id, label),
    CONSTRAINT ck_studio_equipment_feature_position CHECK (position BETWEEN 0 AND 11),
    CONSTRAINT ck_studio_equipment_feature_label_not_blank CHECK (btrim(label) <> '')
);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_feature_equipment
    ON tbl_studio_equipment_feature (equipment_id);

CREATE TABLE IF NOT EXISTS tbl_studio_equipment_photo (
    id uuid NOT NULL,
    equipment_id uuid NOT NULL,
    position integer NOT NULL,
    media_asset_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_equipment_photo PRIMARY KEY (id),
    CONSTRAINT fk_studio_equipment_photo_equipment
        FOREIGN KEY (equipment_id) REFERENCES tbl_studio_equipment (id) ON DELETE CASCADE,
    CONSTRAINT fk_studio_equipment_photo_media
        FOREIGN KEY (media_asset_id) REFERENCES tbl_media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT uk_studio_equipment_photo_position UNIQUE (equipment_id, position),
    CONSTRAINT uk_studio_equipment_photo_asset UNIQUE (equipment_id, media_asset_id),
    CONSTRAINT ck_studio_equipment_photo_position CHECK (position BETWEEN 0 AND 4)
);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_photo_media
    ON tbl_studio_equipment_photo (media_asset_id);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_photo_equipment
    ON tbl_studio_equipment_photo (equipment_id);

CREATE TABLE IF NOT EXISTS tbl_studio_equipment_day (
    id uuid NOT NULL,
    equipment_id uuid NOT NULL,
    availability_date date NOT NULL,
    busy_count integer NOT NULL DEFAULT 0,
    maintenance_count integer NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_equipment_day PRIMARY KEY (id),
    CONSTRAINT fk_studio_equipment_day_equipment
        FOREIGN KEY (equipment_id) REFERENCES tbl_studio_equipment (id) ON DELETE CASCADE,
    CONSTRAINT uk_studio_equipment_day UNIQUE (equipment_id, availability_date),
    CONSTRAINT ck_studio_equipment_day_counts
        CHECK (busy_count >= 0 AND maintenance_count >= 0),
    CONSTRAINT ck_studio_equipment_day_non_default
        CHECK (busy_count + maintenance_count > 0),
    CONSTRAINT ck_studio_equipment_day_version CHECK (version >= 0)
);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_day_range
    ON tbl_studio_equipment_day (equipment_id, availability_date);

CREATE TABLE IF NOT EXISTS tbl_studio_equipment_availability_change (
    id uuid NOT NULL,
    equipment_id uuid NOT NULL,
    actor_id uuid NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    source_bucket varchar(16) NOT NULL,
    target_bucket varchar(16) NOT NULL,
    quantity integer NOT NULL,
    client_request_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_studio_equipment_availability_change PRIMARY KEY (id),
    CONSTRAINT fk_studio_equipment_change_equipment
        FOREIGN KEY (equipment_id) REFERENCES tbl_studio_equipment (id) ON DELETE RESTRICT,
    CONSTRAINT fk_studio_equipment_change_actor
        FOREIGN KEY (actor_id) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT uk_studio_equipment_availability_request
        UNIQUE (equipment_id, client_request_id),
    CONSTRAINT ck_studio_equipment_change_range CHECK (start_date <= end_date),
    CONSTRAINT ck_studio_equipment_change_buckets CHECK (
        source_bucket IN ('AVAILABLE', 'BUSY', 'MAINTENANCE')
        AND target_bucket IN ('AVAILABLE', 'BUSY', 'MAINTENANCE')
        AND source_bucket <> target_bucket
    ),
    CONSTRAINT ck_studio_equipment_change_quantity CHECK (quantity BETWEEN 1 AND 999)
);

CREATE INDEX IF NOT EXISTS idx_studio_equipment_change_history
    ON tbl_studio_equipment_availability_change (equipment_id, created_at);

-- Day rows are mutable calendar projections, not audit records. The immutable
-- change table above retains history, so expired projections can be removed.
-- The application repeats this cleanup opportunistically under the equipment
-- lock on successful owner writes, keeping active calendars bounded to the
-- supported 730-day horizon.
DELETE FROM tbl_studio_equipment_day day
USING tbl_studio_equipment equipment, tbl_studio_profile studio
WHERE day.equipment_id = equipment.id
  AND equipment.studio_profile_id = studio.id
  AND day.availability_date
      < (CURRENT_TIMESTAMP AT TIME ZONE studio.time_zone)::date;

CREATE OR REPLACE FUNCTION soundconnect_validate_studio_equipment_day_capacity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    equipment_capacity integer;
    equipment_archived_at timestamp with time zone;
BEGIN
    SELECT total_quantity, archived_at
      INTO equipment_capacity, equipment_archived_at
     FROM tbl_studio_equipment
     WHERE id = NEW.equipment_id
     FOR UPDATE;

    IF equipment_capacity IS NULL THEN
        RAISE EXCEPTION 'studio equipment does not exist'
            USING ERRCODE = '23503';
    END IF;
    IF equipment_archived_at IS NOT NULL THEN
        RAISE EXCEPTION 'archived studio equipment calendar cannot be changed'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_studio_equipment_day_active_equipment';
    END IF;
    IF NEW.busy_count + NEW.maintenance_count > equipment_capacity THEN
        RAISE EXCEPTION 'equipment day allocation exceeds total quantity'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_studio_equipment_day_capacity';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_studio_equipment_day_capacity
    ON tbl_studio_equipment_day;
CREATE TRIGGER trg_studio_equipment_day_capacity
BEFORE INSERT OR UPDATE OF equipment_id, busy_count, maintenance_count
ON tbl_studio_equipment_day
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_studio_equipment_day_capacity();

CREATE OR REPLACE FUNCTION soundconnect_validate_studio_equipment_total_quantity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    studio_local_today date;
BEGIN
    SELECT (CURRENT_TIMESTAMP AT TIME ZONE studio.time_zone)::date
      INTO studio_local_today
      FROM tbl_studio_profile studio
     WHERE studio.id = NEW.studio_profile_id;

    IF studio_local_today IS NULL THEN
        RAISE EXCEPTION 'studio profile does not exist'
            USING ERRCODE = '23503';
    END IF;

    IF NEW.total_quantity < OLD.total_quantity
       AND EXISTS (
           SELECT 1
             FROM tbl_studio_equipment_day day
            WHERE day.equipment_id = NEW.id
              AND day.availability_date >= studio_local_today
              AND day.busy_count + day.maintenance_count > NEW.total_quantity
       ) THEN
        RAISE EXCEPTION 'equipment total quantity is below a current or future day allocation'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_studio_equipment_total_covers_calendar';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_studio_equipment_total_quantity
    ON tbl_studio_equipment;
CREATE TRIGGER trg_studio_equipment_total_quantity
BEFORE UPDATE OF total_quantity ON tbl_studio_equipment
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_studio_equipment_total_quantity();

-- ---------------------------------------------------------------------------
-- Owner catalog requests and proposed root children
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tbl_backline_category_request (
    id uuid NOT NULL,
    studio_profile_id uuid NOT NULL,
    requested_by_user_id uuid NOT NULL,
    client_request_id uuid NOT NULL,
    request_payload_hash varchar(64) NOT NULL,
    request_type varchar(24) NOT NULL,
    requested_name varchar(160) NOT NULL,
    normalized_requested_name varchar(160) NOT NULL,
    requester_note varchar(300),
    parent_category_id uuid,
    status varchar(16) NOT NULL DEFAULT 'PENDING',
    reviewed_by_user_id uuid,
    reviewed_at timestamp with time zone,
    decision_note varchar(500),
    resolved_root_category_id uuid,
    resolved_category_id uuid,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_backline_category_request PRIMARY KEY (id),
    CONSTRAINT fk_backline_category_request_studio
        FOREIGN KEY (studio_profile_id) REFERENCES tbl_studio_profile (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backline_category_request_requester
        FOREIGN KEY (requested_by_user_id) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backline_category_request_parent
        FOREIGN KEY (parent_category_id) REFERENCES tbl_backline_category (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backline_category_request_reviewer
        FOREIGN KEY (reviewed_by_user_id) REFERENCES tbl_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backline_category_request_resolved_root
        FOREIGN KEY (resolved_root_category_id) REFERENCES tbl_backline_category (id) ON DELETE RESTRICT,
    CONSTRAINT fk_backline_category_request_resolved_category
        FOREIGN KEY (resolved_category_id) REFERENCES tbl_backline_category (id) ON DELETE RESTRICT,
    CONSTRAINT uk_backline_category_request_client
        UNIQUE (studio_profile_id, client_request_id),
    CONSTRAINT ck_backline_category_request_payload_hash
        CHECK (request_payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_backline_category_request_type
        CHECK (request_type IN ('ROOT_CATEGORY', 'SUBCATEGORY')),
    CONSTRAINT ck_backline_category_request_shape CHECK (
        (request_type = 'ROOT_CATEGORY' AND parent_category_id IS NULL)
        OR (request_type = 'SUBCATEGORY' AND parent_category_id IS NOT NULL)
    ),
    CONSTRAINT ck_backline_category_request_name CHECK (
        btrim(requested_name) <> '' AND btrim(normalized_requested_name) <> ''
    ),
    CONSTRAINT ck_backline_category_request_note CHECK (
        requester_note IS NULL OR btrim(requester_note) <> ''
    ),
    CONSTRAINT ck_backline_category_request_status CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')
    ),
    CONSTRAINT ck_backline_category_request_decision CHECK (
        (status = 'PENDING'
            AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL
            AND resolved_root_category_id IS NULL AND resolved_category_id IS NULL)
        OR (status = 'APPROVED'
            AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL
            AND resolved_root_category_id IS NOT NULL AND resolved_category_id IS NOT NULL)
        OR (status = 'REJECTED'
            AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL
            AND resolved_root_category_id IS NULL AND resolved_category_id IS NULL)
        OR (status = 'WITHDRAWN'
            AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL
            AND resolved_root_category_id IS NULL AND resolved_category_id IS NULL)
    ),
    CONSTRAINT ck_backline_category_request_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_backline_category_request_pending_equivalent
    ON tbl_backline_category_request (
        studio_profile_id,
        request_type,
        coalesce(parent_category_id, '00000000-0000-0000-0000-000000000000'::uuid),
        normalized_requested_name
    )
    WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_backline_request_studio_status
    ON tbl_backline_category_request (studio_profile_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_backline_request_admin_status
    ON tbl_backline_category_request (status, created_at);

CREATE INDEX IF NOT EXISTS idx_backline_request_studio_created
    ON tbl_backline_category_request (studio_profile_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_backline_request_admin_created
    ON tbl_backline_category_request (created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION soundconnect_validate_backline_category_request_parent()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_level smallint;
    parent_active boolean;
BEGIN
    IF NEW.request_type = 'ROOT_CATEGORY' THEN
        RETURN NEW;
    END IF;

    SELECT level, active INTO parent_level, parent_active
      FROM tbl_backline_category
     WHERE id = NEW.parent_category_id;

    IF parent_level IS NULL OR parent_level <> 0 OR NOT parent_active THEN
        RAISE EXCEPTION 'subcategory request requires an active root category'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_request_active_root';
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_backline_category_request_parent
    ON tbl_backline_category_request;
CREATE TRIGGER trg_backline_category_request_parent
BEFORE INSERT OR UPDATE OF request_type, parent_category_id
ON tbl_backline_category_request
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_backline_category_request_parent();

CREATE TABLE IF NOT EXISTS tbl_backline_category_request_child (
    id uuid NOT NULL,
    request_id uuid NOT NULL,
    position integer NOT NULL,
    name varchar(160) NOT NULL,
    normalized_name varchar(160) NOT NULL,
    resolved_category_id uuid,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_backline_category_request_child PRIMARY KEY (id),
    CONSTRAINT fk_backline_category_request_child_request
        FOREIGN KEY (request_id) REFERENCES tbl_backline_category_request (id) ON DELETE CASCADE,
    CONSTRAINT fk_backline_category_request_child_result
        FOREIGN KEY (resolved_category_id) REFERENCES tbl_backline_category (id) ON DELETE RESTRICT,
    CONSTRAINT uk_backline_request_child_position UNIQUE (request_id, position),
    CONSTRAINT uk_backline_request_child_name UNIQUE (request_id, normalized_name),
    CONSTRAINT ck_backline_category_request_child_position CHECK (position BETWEEN 0 AND 9),
    CONSTRAINT ck_backline_category_request_child_name CHECK (
        btrim(name) <> '' AND btrim(normalized_name) <> ''
    )
);

CREATE INDEX IF NOT EXISTS idx_backline_request_child_request
    ON tbl_backline_category_request_child (request_id);

CREATE OR REPLACE FUNCTION soundconnect_validate_backline_request_child()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    parent_request_type varchar(24);
    request_status varchar(16);
BEGIN
    SELECT request_type, status INTO parent_request_type, request_status
      FROM tbl_backline_category_request
     WHERE id = NEW.request_id;

    IF parent_request_type IS NULL OR parent_request_type <> 'ROOT_CATEGORY' THEN
        RAISE EXCEPTION 'proposed children belong only to pending root category requests'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_request_child_parent';
    END IF;

    IF TG_OP = 'INSERT' AND request_status <> 'PENDING' THEN
        RAISE EXCEPTION 'new proposed children belong only to pending root category requests'
            USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_request_child_parent';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF NEW.request_id IS DISTINCT FROM OLD.request_id
           OR NEW.position IS DISTINCT FROM OLD.position
           OR NEW.name IS DISTINCT FROM OLD.name
           OR NEW.normalized_name IS DISTINCT FROM OLD.normalized_name THEN
            RAISE EXCEPTION 'proposed child identity is immutable'
                USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_request_child_immutable';
        END IF;
        IF request_status NOT IN ('PENDING', 'APPROVED') THEN
            RAISE EXCEPTION 'only pending or approved requests can resolve proposed children'
                USING ERRCODE = '23514', CONSTRAINT = 'ck_backline_category_request_child_parent';
        END IF;
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_backline_category_request_child
    ON tbl_backline_category_request_child;
CREATE TRIGGER trg_backline_category_request_child
BEFORE INSERT OR UPDATE
ON tbl_backline_category_request_child
FOR EACH ROW
EXECUTE FUNCTION soundconnect_validate_backline_request_child();

-- Permission UUID is stable and does not depend on pgcrypto.
INSERT INTO tbl_permissions (id, name, created_at, updated_at)
VALUES
    ('9a0a90ca-811f-4e09-9f50-9dd4c357334b', 'MANAGE_BACKLINE_CATALOG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('72e544d9-c278-4ef8-86cd-d32b528689d5', 'MANAGE_STUDIO_APPLICATIONS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (name) DO NOTHING;

-- Runtime bootstrapping can be disabled in production. Grant the new
-- authority during the migration as well so catalog review is usable
-- immediately after deployment. ROLE_OWNER intentionally mirrors the
-- application's existing "all permissions" policy.
INSERT INTO role_permissions (role_id, permission_id)
SELECT role.id, permission.id
  FROM tbl_role role
  JOIN tbl_permissions permission
    ON permission.name IN ('MANAGE_BACKLINE_CATALOG', 'MANAGE_STUDIO_APPLICATIONS')
 WHERE role.name IN ('ROLE_ADMIN', 'ROLE_OWNER')
   AND NOT EXISTS (
       SELECT 1
         FROM role_permissions existing
        WHERE existing.role_id = role.id
          AND existing.permission_id = permission.id
   )
ON CONFLICT DO NOTHING;

COMMIT;
