-- Correct the pre-release TableGroup join-request notification type spelling.
--
-- PostgreSQL CHECK constraint names generated by Hibernate are not stable across
-- schema histories. Discover constraints by table, referenced column, and
-- definition so every existing name and validation state is preserved.

BEGIN;

DO $$
BEGIN
    IF to_regclass(format('%I.%I', current_schema(), 'tbl_notification')) IS NULL THEN
        RAISE EXCEPTION
            'TableGroup notification type spelling migration requires tbl_notification';
    END IF;
    IF to_regclass(format('%I.%I', current_schema(), 'tbl_table_group_notification_outbox')) IS NULL THEN
        RAISE EXCEPTION
            'TableGroup notification type spelling migration requires tbl_table_group_notification_outbox';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = current_schema()
           AND table_name = 'tbl_notification'
           AND column_name = 'type'
           AND data_type IN ('character varying', 'text')
    ) THEN
        RAISE EXCEPTION
            'TableGroup notification type spelling migration requires tbl_notification.type as text';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = current_schema()
           AND table_name = 'tbl_table_group_notification_outbox'
           AND column_name = 'notification_type'
           AND data_type IN ('character varying', 'text')
    ) THEN
        RAISE EXCEPTION
            'TableGroup notification type spelling migration requires tbl_table_group_notification_outbox.notification_type as text';
    END IF;
END $$;

LOCK TABLE tbl_notification IN ACCESS EXCLUSIVE MODE;
LOCK TABLE tbl_table_group_notification_outbox IN ACCESS EXCLUSIVE MODE;

CREATE TEMPORARY TABLE table_group_notification_type_constraint_rewrite (
    table_name text NOT NULL,
    constraint_name name NOT NULL,
    constraint_definition text NOT NULL,
    was_validated boolean NOT NULL,
    PRIMARY KEY (table_name, constraint_name)
) ON COMMIT DROP;

INSERT INTO table_group_notification_type_constraint_rewrite (
    table_name,
    constraint_name,
    constraint_definition,
    was_validated
)
SELECT relation.relname,
       constraint_entry.conname,
       pg_get_constraintdef(constraint_entry.oid, true),
       constraint_entry.convalidated
  FROM pg_constraint constraint_entry
  JOIN pg_class relation
    ON relation.oid = constraint_entry.conrelid
  JOIN pg_namespace namespace_entry
    ON namespace_entry.oid = relation.relnamespace
  JOIN pg_attribute column_entry
    ON column_entry.attrelid = relation.oid
   AND column_entry.attname = CASE relation.relname
       WHEN 'tbl_notification' THEN 'type'
       WHEN 'tbl_table_group_notification_outbox' THEN 'notification_type'
   END
   AND NOT column_entry.attisdropped
 WHERE namespace_entry.nspname = current_schema()
   AND relation.relname IN (
       'tbl_notification',
       'tbl_table_group_notification_outbox'
   )
   AND constraint_entry.contype = 'c'
   AND column_entry.attnum = ANY (constraint_entry.conkey)
   AND strpos(
       pg_get_constraintdef(constraint_entry.oid, true),
       'TABLE_JOIN_REQUEST_RECEVIED'
   ) > 0;

DO $$
DECLARE
    target record;
BEGIN
    FOR target IN
        SELECT table_name, constraint_name
          FROM table_group_notification_type_constraint_rewrite
         ORDER BY table_name, constraint_name
    LOOP
        EXECUTE format(
            'ALTER TABLE %I.%I DROP CONSTRAINT %I',
            current_schema(),
            target.table_name,
            target.constraint_name
        );
    END LOOP;
END $$;

UPDATE tbl_notification
   SET type = 'TABLE_JOIN_REQUEST_RECEIVED'
 WHERE type = 'TABLE_JOIN_REQUEST_RECEVIED';

UPDATE tbl_table_group_notification_outbox
   SET notification_type = 'TABLE_JOIN_REQUEST_RECEIVED'
 WHERE notification_type = 'TABLE_JOIN_REQUEST_RECEVIED';

DO $$
DECLARE
    target record;
    corrected_definition text;
BEGIN
    FOR target IN
        SELECT table_name,
               constraint_name,
               constraint_definition,
               was_validated
          FROM table_group_notification_type_constraint_rewrite
         ORDER BY table_name, constraint_name
    LOOP
        corrected_definition := replace(
            target.constraint_definition,
            'TABLE_JOIN_REQUEST_RECEVIED',
            'TABLE_JOIN_REQUEST_RECEIVED'
        );
        corrected_definition := regexp_replace(
            corrected_definition,
            '[[:space:]]+NOT VALID[[:space:]]*$',
            '',
            'i'
        );

        EXECUTE format(
            'ALTER TABLE %I.%I ADD CONSTRAINT %I %s NOT VALID',
            current_schema(),
            target.table_name,
            target.constraint_name,
            corrected_definition
        );

        IF target.was_validated THEN
            EXECUTE format(
                'ALTER TABLE %I.%I VALIDATE CONSTRAINT %I',
                current_schema(),
                target.table_name,
                target.constraint_name
            );
        END IF;
    END LOOP;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM tbl_notification
         WHERE type = 'TABLE_JOIN_REQUEST_RECEVIED'
    ) OR EXISTS (
        SELECT 1
          FROM tbl_table_group_notification_outbox
         WHERE notification_type = 'TABLE_JOIN_REQUEST_RECEVIED'
    ) THEN
        RAISE EXCEPTION
            'TableGroup notification type spelling migration left legacy values behind';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_constraint constraint_entry
          JOIN pg_class relation
            ON relation.oid = constraint_entry.conrelid
          JOIN pg_namespace namespace_entry
            ON namespace_entry.oid = relation.relnamespace
         WHERE namespace_entry.nspname = current_schema()
           AND relation.relname IN (
               'tbl_notification',
               'tbl_table_group_notification_outbox'
           )
           AND constraint_entry.contype = 'c'
           AND strpos(
               pg_get_constraintdef(constraint_entry.oid, true),
               'TABLE_JOIN_REQUEST_RECEVIED'
           ) > 0
    ) THEN
        RAISE EXCEPTION
            'TableGroup notification type spelling migration left legacy CHECK constraints behind';
    END IF;
END $$;

COMMIT;
