-- Run before the new backend when production uses ddl-auto=validate.
-- Calendar visibility defaults to enabled for both existing and newly-created
-- musician profiles; absent settings rows have exactly the same semantics.
-- No event is copied or backfilled. Approved direct/band links remain the source.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS tbl_musician_calendar_settings (
    musician_profile_id uuid PRIMARY KEY,
    visible boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_musician_calendar_version CHECK (version >= 0),
    CONSTRAINT fk_musician_calendar_profile FOREIGN KEY (musician_profile_id)
        REFERENCES tbl_musician_profile (id) ON DELETE CASCADE
);

-- Normalize a table previously generated by Hibernate as well as a fresh one.
ALTER TABLE tbl_musician_calendar_settings
    ALTER COLUMN visible SET DEFAULT true,
    ALTER COLUMN visible SET NOT NULL,
    ALTER COLUMN version SET DEFAULT 0,
    ALTER COLUMN version SET NOT NULL,
    DROP CONSTRAINT IF EXISTS ck_musician_calendar_version;
ALTER TABLE tbl_musician_calendar_settings
    ADD CONSTRAINT ck_musician_calendar_version CHECK (version >= 0);
DO $$
DECLARE existing_fk record;
BEGIN
    FOR existing_fk IN
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'tbl_musician_calendar_settings'::regclass AND contype = 'f'
          AND confrelid = 'tbl_musician_profile'::regclass
    LOOP
        EXECUTE format('ALTER TABLE tbl_musician_calendar_settings DROP CONSTRAINT %I', existing_fk.conname);
    END LOOP;
    ALTER TABLE tbl_musician_calendar_settings
        ADD CONSTRAINT fk_musician_calendar_profile FOREIGN KEY (musician_profile_id)
        REFERENCES tbl_musician_profile (id) ON DELETE CASCADE;
END $$;

-- Preserve already saved preferences on re-run.
INSERT INTO tbl_musician_calendar_settings (musician_profile_id)
SELECT id FROM tbl_musician_profile
ON CONFLICT (musician_profile_id) DO NOTHING;

CREATE INDEX IF NOT EXISTS ix_event_musician_calendar
    ON tbl_event (musician_profile_id, event_date, start_time, id)
    WHERE performer_approval_status = 'APPROVED' AND musician_profile_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_event_band_calendar
    ON tbl_event (band_id, event_date, start_time, id)
    WHERE performer_approval_status = 'APPROVED' AND band_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_band_member_calendar
    ON tbl_band_member (user_id, band_id) WHERE status = 'ACTIVE';
-- The OR/EXISTS calendar query can always restrict by its bounded date window.
CREATE INDEX IF NOT EXISTS ix_event_approved_calendar_date
    ON tbl_event (event_date, start_time, id) WHERE performer_approval_status = 'APPROVED';

COMMIT;
