-- Run before the musician-feed backend when production uses ddl-auto=validate.
-- This is deliberately an additive, private preference table. It neither moves
-- nor copies residence/venue data and it does not alter Location or Collab rows.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS tbl_musician_feed_preferences (
    musician_profile_id uuid PRIMARY KEY,
    opportunity_city_id uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_musician_feed_preferences_version
        CHECK (version >= 0 AND version < 9223372036854775807),
    CONSTRAINT fk_musician_feed_preferences_profile
        FOREIGN KEY (musician_profile_id) REFERENCES tbl_musician_profile(id) ON DELETE CASCADE,
    CONSTRAINT fk_musician_feed_preferences_city
        FOREIGN KEY (opportunity_city_id) REFERENCES tbl_city(id) ON DELETE SET NULL
);

-- Normalize a table that a local Hibernate `update` run may have created first.
ALTER TABLE tbl_musician_feed_preferences
    ADD COLUMN IF NOT EXISTS opportunity_city_id uuid,
    ADD COLUMN IF NOT EXISTS version bigint;
UPDATE tbl_musician_feed_preferences SET version = 0 WHERE version IS NULL;
ALTER TABLE tbl_musician_feed_preferences
    ALTER COLUMN opportunity_city_id DROP NOT NULL,
    ALTER COLUMN version SET DEFAULT 0,
    ALTER COLUMN version SET NOT NULL,
    DROP CONSTRAINT IF EXISTS ck_musician_feed_preferences_version;
ALTER TABLE tbl_musician_feed_preferences
    ADD CONSTRAINT ck_musician_feed_preferences_version
        CHECK (version >= 0 AND version < 9223372036854775807);

-- Constraint names generated by Hibernate are not stable. Replace only foreign
-- keys to the two authoritative parents and preserve every unrelated constraint.
DO $migration$
DECLARE existing_fk record;
BEGIN
    FOR existing_fk IN
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'tbl_musician_feed_preferences'::regclass
          AND contype = 'f'
          AND confrelid IN ('tbl_musician_profile'::regclass, 'tbl_city'::regclass)
    LOOP
        EXECUTE format('ALTER TABLE tbl_musician_feed_preferences DROP CONSTRAINT %I', existing_fk.conname);
    END LOOP;

    ALTER TABLE tbl_musician_feed_preferences
        ADD CONSTRAINT fk_musician_feed_preferences_profile
            FOREIGN KEY (musician_profile_id) REFERENCES tbl_musician_profile(id) ON DELETE CASCADE,
        ADD CONSTRAINT fk_musician_feed_preferences_city
            FOREIGN KEY (opportunity_city_id) REFERENCES tbl_city(id) ON DELETE SET NULL;
END
$migration$;

CREATE INDEX IF NOT EXISTS ix_musician_feed_preferences_city
    ON tbl_musician_feed_preferences(opportunity_city_id, musician_profile_id)
    WHERE opportunity_city_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS soundconnect_schema_migrations (
    migration_id varchar(160) PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO soundconnect_schema_migrations(migration_id)
VALUES ('2026-09-11-musician-feed-preferences') ON CONFLICT DO NOTHING;

COMMIT;
