package com.berkayb.soundconnect.modules.feed.musician.provider;

import com.berkayb.soundconnect.modules.event.dto.response.EventResponseDto;
import com.berkayb.soundconnect.modules.event.enums.EventOrigin;
import com.berkayb.soundconnect.modules.event.enums.EventVenueApprovalStatus;
import com.berkayb.soundconnect.modules.event.enums.PerformerType;
import com.berkayb.soundconnect.modules.event.publication.EventProfilePublicationRepository;
import com.berkayb.soundconnect.modules.event.support.EventShareUrlBuilder;
import com.berkayb.soundconnect.modules.feed.musician.api.*;
import com.berkayb.soundconnect.modules.feed.musician.candidate.*;
import com.berkayb.soundconnect.modules.overthinking.dto.response.OverthinkingPostResponseDto;
import com.berkayb.soundconnect.modules.overthinking.service.OverthinkingPostService;
import com.berkayb.soundconnect.modules.tablegroup.enums.TableGroupStatus;
import com.berkayb.soundconnect.modules.tablegroup.profileshare.TableGroupProfileShareResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/**
 * Social stories generated by followed users. The provider deliberately performs
 * one bounded identity query and at most one batch projection per target renderer;
 * it never hydrates a card with a per-row repository call.
 */
@Component
public class MusicianFeedMediaActivityCandidateProvider implements MusicianFeedCandidateProvider {
    private static final ZoneId EVENT_ZONE = ZoneId.of("Europe/Istanbul");
    private static final int MAX_VISIBLE_ACTORS = 3;

    private static final String ACTIVITY_SQL = """
            with actor_profile_candidates as (
                select musician.id as profile_id, 'MUSICIAN' as profile_type, account.id as user_id,
                       account.user_name as username,
                       coalesce(musician.stage_name, musician.name, account.user_name) as display_name,
                       musician.profile_picture_media_id as avatar_id, account.profile_picture as legacy_avatar,
                       0 as profile_priority
                from tbl_musician_profile musician join tbl_user account on account.id=musician.user_id
                    and account.status='ACTIVE' and account.email_verified and account.erased_at is null
                union all
                select listener.id, 'LISTENER', account.id, account.user_name,
                       coalesce(listener.name, account.user_name), listener.profile_picture_media_id,
                       account.profile_picture, 1
                from \"tbl_listener-profile\" listener join tbl_user account on account.id=listener.user_id
                    and account.status='ACTIVE' and account.email_verified and account.erased_at is null
                where listener.visibility_mode='STANDARD' and listener.visibility_choice_completed
                  and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=account.id and role.name='ROLE_LISTENER')
                  and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=account.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                          'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
                  and not exists(select 1 from tbl_musician_profile profile where profile.user_id=account.id)
                  and not exists(select 1 from tbl_studio_profile profile where profile.user_id=account.id)
                  and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=account.id)
                  and not exists(select 1 from tbl_producer_profile profile where profile.user_id=account.id)
                  and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=account.id)
                union all
                select studio.id, 'STUDIO', account.id, account.user_name,
                       coalesce(studio.name, account.user_name), studio.profile_picture_media_id,
                       account.profile_picture, 2
                from tbl_studio_profile studio join tbl_user account on account.id=studio.user_id
                    and account.status='ACTIVE' and account.email_verified and account.erased_at is null
                union all
                select venue.id, 'VENUE', account.id, account.user_name, venue.name,
                       venue_profile.profile_picture_media_id, account.profile_picture, 3
                from tbl_venue_profile venue_profile join tbl_venues venue on venue.id=venue_profile.venue_id
                join tbl_user account on account.id=venue.owner_id and account.status='ACTIVE'
                    and account.email_verified and account.erased_at is null
                where venue.status='APPROVED'
            ), actor_profiles as (
                select profile_id, profile_type, user_id, username, display_name, avatar_id, legacy_avatar
                from (select candidate.*, row_number() over (
                    partition by user_id order by profile_priority, profile_id) as profile_rank
                    from actor_profile_candidates candidate) ranked
                where profile_rank=1
            ), media_access as (
                select 'MEDIA'::varchar as target_type, media.id as target_id
                from tbl_media_asset media
                join lateral (
                    select track.id as publication_id, 0 as priority
                    from tbl_tracks track
                    where :includeTracks and track.media_asset_id=media.id
                      and track.owner_type=media.owner_type and track.owner_id=media.owner_id
                      and track.owner_type in ('MUSICIAN_PROFILE','LISTENER_PROFILE','STUDIO_PROFILE',
                          'VENUE_PROFILE','BAND')
                    union all
                    select attachment.id, 1
                    from tbl_profile_media attachment
                    where :includeProfileMedia and attachment.media_asset_id=media.id
                      and media.owner_id=attachment.profile_id
                      and media.owner_type=case attachment.profile_type
                          when 'MUSICIAN' then 'MUSICIAN_PROFILE'
                          when 'LISTENER' then 'LISTENER_PROFILE'
                          when 'STUDIO' then 'STUDIO_PROFILE'
                          when 'VENUE' then 'VENUE_PROFILE'
                          when 'BAND' then 'BAND' end
                      and attachment.profile_type in ('MUSICIAN','LISTENER','STUDIO','VENUE','BAND')
                      and attachment.role in ('GALLERY','FEATURED_VIDEO','INTRO_VIDEO')
                    order by priority, publication_id limit 1
                ) publication on true
                where :includeMedia and media.status='READY' and media.visibility='PUBLIC'
                  and coalesce(nullif(trim(media.playback_url),''), nullif(trim(media.source_url),'')) is not null
                  and (
                    (media.owner_type='MUSICIAN_PROFILE' and exists(select 1 from tbl_musician_profile profile
                        join tbl_user owner_account on owner_account.id=profile.user_id
                          and owner_account.status='ACTIVE' and owner_account.email_verified
                          and owner_account.erased_at is null
                        where profile.id=media.owner_id and owner_account.id<>:viewerId))
                    or (media.owner_type='STUDIO_PROFILE' and exists(select 1 from tbl_studio_profile profile
                        join tbl_user owner_account on owner_account.id=profile.user_id
                          and owner_account.status='ACTIVE' and owner_account.email_verified
                          and owner_account.erased_at is null
                        where profile.id=media.owner_id and owner_account.id<>:viewerId))
                    or (media.owner_type='LISTENER_PROFILE' and exists(select 1 from \"tbl_listener-profile\" profile
                        join tbl_user owner_account on owner_account.id=profile.user_id
                          and owner_account.status='ACTIVE' and owner_account.email_verified
                          and owner_account.erased_at is null
                        where profile.id=media.owner_id and owner_account.id<>:viewerId
                          and profile.visibility_mode='STANDARD' and profile.visibility_choice_completed
                          and exists(select 1 from user_roles membership join tbl_role role
                              on role.id=membership.role_id where membership.user_id=owner_account.id
                              and role.name='ROLE_LISTENER')
                          and not exists(select 1 from user_roles membership join tbl_role role
                              on role.id=membership.role_id where membership.user_id=owner_account.id
                              and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN','ROLE_VENUE',
                                  'ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
                          and not exists(select 1 from tbl_musician_profile p where p.user_id=owner_account.id)
                          and not exists(select 1 from tbl_studio_profile p where p.user_id=owner_account.id)
                          and not exists(select 1 from tbl_organizer_profile p where p.user_id=owner_account.id)
                          and not exists(select 1 from tbl_producer_profile p where p.user_id=owner_account.id)
                          and not exists(select 1 from tbl_venues v where v.owner_id=owner_account.id)))
                    or (media.owner_type='VENUE_PROFILE' and exists(select 1 from tbl_venue_profile profile
                        join tbl_venues venue on venue.id=profile.venue_id and venue.status='APPROVED'
                        join tbl_user owner_account on owner_account.id=venue.owner_id
                          and owner_account.status='ACTIVE' and owner_account.email_verified
                          and owner_account.erased_at is null
                        where profile.id=media.owner_id and owner_account.id<>:viewerId))
                    or (media.owner_type='BAND'
                        and exists(select 1 from tbl_band_member public_member
                          join tbl_user member_account on member_account.id=public_member.user_id
                            and member_account.status='ACTIVE' and member_account.email_verified
                            and member_account.erased_at is null
                          where public_member.band_id=media.owner_id and public_member.status='ACTIVE')
                        and not exists(select 1 from tbl_band_member own_member where own_member.band_id=media.owner_id
                          and own_member.user_id=:viewerId and own_member.status='ACTIVE')))
            ), event_access as (
                select 'EVENT'::varchar as target_type, event.id as target_id
                from tbl_event event join tbl_venues venue on venue.id=event.venue_id
                join tbl_user venue_owner on venue_owner.id=venue.owner_id
                join tbl_city city on city.id=venue.city_id
                join tbl_district district on district.id=venue.district_id and district.city_id=city.id
                join tbl_neighborhood neighborhood on neighborhood.id=venue.neighborhood_id
                    and neighborhood.district_id=district.id
                where :includeEvents and event.event_origin='VENUE' and event.venue_calendar_approved
                  and event.performer_approval_status in ('APPROVED','NOT_REQUIRED')
                  and venue.status='APPROVED' and venue_owner.status='ACTIVE'
                  and venue_owner.email_verified and venue_owner.erased_at is null
                  and event.event_date is not null and event.start_time is not null
                  and (event.event_date>:today or (event.event_date=:today and %s>:nowSeconds))
                  and not exists(select 1 from event_performer_requests pending
                      where pending.event_id=event.id and pending.status='PENDING')
                  and (event.musician_profile_id is null or exists(select 1 from tbl_musician_profile performer
                      join tbl_user performer_account on performer_account.id=performer.user_id
                        and performer_account.status='ACTIVE' and performer_account.email_verified
                        and performer_account.erased_at is null
                      where performer.id=event.musician_profile_id))
                  and (event.band_id is null or exists(select 1 from tbl_band_member public_member
                      join tbl_user member_account on member_account.id=public_member.user_id
                        and member_account.status='ACTIVE' and member_account.email_verified
                        and member_account.erased_at is null
                      where public_member.band_id=event.band_id and public_member.status='ACTIVE'))
                  and event.organizer_user_id<>:viewerId
                  and not (event.profile_calendar_approved and exists(select 1 from tbl_musician_profile own_profile
                      where own_profile.id=event.musician_profile_id and own_profile.user_id=:viewerId))
                  and not exists(select 1 from tbl_band_member own_member where own_member.band_id=event.band_id
                      and own_member.user_id=:viewerId and own_member.status='ACTIVE')
                  and not exists(select 1 from event_member_publications own_publication
                      join tbl_musician_profile own_profile on own_profile.id=own_publication.musician_profile_id
                      where own_publication.event_id=event.id and own_publication.visible
                        and own_profile.user_id=:viewerId)
            ), event_post_access as (
                select 'EVENT_POST'::varchar as target_type, intent.post_id as target_id
                from tbl_event_audience_intent intent
                join tbl_user publisher on publisher.id=intent.user_id
                join \"tbl_listener-profile\" listener on listener.user_id=publisher.id
                    and listener.visibility_mode='STANDARD' and listener.visibility_choice_completed
                join tbl_event event on event.id=intent.event_id
                join tbl_venues venue on venue.id=event.venue_id
                join tbl_user venue_owner on venue_owner.id=venue.owner_id
                join tbl_city city on city.id=venue.city_id
                join tbl_district district on district.id=venue.district_id and district.city_id=city.id
                join tbl_neighborhood neighborhood on neighborhood.id=venue.neighborhood_id
                    and neighborhood.district_id=district.id
                where :includeEventPosts and intent.published_on_profile and intent.intent<>'NONE'
                  and intent.published_at<=:anchor
                  and intent.post_id is not null and publisher.id<>:viewerId
                  and publisher.status='ACTIVE' and publisher.email_verified and publisher.erased_at is null
                  and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=publisher.id and role.name='ROLE_LISTENER')
                  and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=publisher.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                          'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
                  and not exists(select 1 from tbl_musician_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_studio_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_producer_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=publisher.id)
                  and event.event_origin='VENUE' and event.venue_calendar_approved
                  and event.performer_approval_status in ('APPROVED','NOT_REQUIRED')
                  and venue.status='APPROVED' and venue_owner.status='ACTIVE'
                  and venue_owner.email_verified and venue_owner.erased_at is null
                  and event.event_date is not null and event.start_time is not null
                  and (event.event_date>:today or (event.event_date=:today and %s>:nowSeconds))
                  and not exists(select 1 from event_performer_requests pending
                      where pending.event_id=event.id and pending.status='PENDING')
                  and (event.musician_profile_id is null or exists(select 1 from tbl_musician_profile performer
                      join tbl_user performer_account on performer_account.id=performer.user_id
                        and performer_account.status='ACTIVE' and performer_account.email_verified
                        and performer_account.erased_at is null
                      where performer.id=event.musician_profile_id))
                  and (event.band_id is null or exists(select 1 from tbl_band_member public_member
                      join tbl_user member_account on member_account.id=public_member.user_id
                        and member_account.status='ACTIVE' and member_account.email_verified
                        and member_account.erased_at is null
                      where public_member.band_id=event.band_id and public_member.status='ACTIVE'))
            ), table_post_access as (
                select 'TABLE_GROUP_POST'::varchar as target_type, share.id as target_id
                from tbl_table_group_profile_share share
                join tbl_user publisher on publisher.id=share.owner_user_id
                join \"tbl_listener-profile\" listener on listener.id=share.listener_profile_id
                    and listener.user_id=publisher.id and listener.visibility_mode='STANDARD'
                    and listener.visibility_choice_completed
                join tbl_table_group table_group on table_group.id=share.table_group_id
                where :includeTablePosts and share.published_at<=:anchor and publisher.id<>:viewerId
                  and publisher.status='ACTIVE' and publisher.email_verified and publisher.erased_at is null
                  and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=publisher.id and role.name='ROLE_LISTENER')
                  and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=publisher.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                          'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
                  and not exists(select 1 from tbl_musician_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_studio_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_producer_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=publisher.id)
                  and (share.final_source is not null or (not share.final_source_frozen
                      and table_group.status='ACTIVE' and table_group.expires_at>:readAt
                      and (table_group.owner_id=share.owner_user_id or exists (
                        select 1 from tbl_table_group_participants eligible
                        where eligible.table_group_id=table_group.id
                          and eligible.user_id=share.owner_user_id and eligible.status='ACCEPTED'))))
            ), overthinking_post_access as (
                select 'OVERTHINKING_PROFILE_SHARE'::varchar as target_type, share.id as target_id
                from tbl_overthinking_profile_share share
                join tbl_user publisher on publisher.id=share.owner_user_id
                join \"tbl_listener-profile\" listener on listener.id=share.listener_profile_id
                    and listener.user_id=publisher.id and listener.visibility_mode='STANDARD'
                    and listener.visibility_choice_completed
                join tbl_overthinking_post source on source.id=share.source_post_id
                where :includeOverthinkingPosts and share.published_at<=:anchor and publisher.id<>:viewerId
                  and publisher.status='ACTIVE' and publisher.email_verified and publisher.erased_at is null
                  and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=publisher.id and role.name='ROLE_LISTENER')
                  and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                      where membership.user_id=publisher.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                          'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
                  and not exists(select 1 from tbl_musician_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_studio_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_producer_profile profile where profile.user_id=publisher.id)
                  and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=publisher.id)
            ), target_access as (
                select * from media_access union all select * from event_access
                union all select * from event_post_access union all select * from table_post_access
                union all select * from overthinking_post_access
            ), raw_activity as (
                select likes.id as activity_id, likes.user_id as actor_user_id, likes.target_type,
                       likes.target_id, likes.created_at as occurred_at, 'LIKE'::varchar as action
                from tbl_like likes
                where :includeLikes and likes.target_type in (:targetTypes) and likes.created_at<=:anchor
                union all
                select comments.id, comments.user_id, comments.target_type, comments.target_id,
                       comments.created_at, 'COMMENT'::varchar
                from tbl_comment comments
                where :includeComments and not comments.is_deleted
                  and comments.target_type in (:targetTypes) and comments.created_at<=:anchor
            ), eligible as (
                select activity.*, actor_profile.profile_id as actor_profile_id,
                       actor_profile.profile_type as actor_profile_type,
                       actor_profile.username as actor_username,
                       actor_profile.display_name as actor_display_name,
                       coalesce(actor_avatar.playback_url, actor_avatar.source_url,
                                actor_avatar.thumbnail_url, actor_profile.legacy_avatar) as actor_avatar_url,
                       case when activity.action='COMMENT' then 'ACTIVITY_COMMENT:' || activity.activity_id::text
                            else 'ACTIVITY_LIKE:' || activity.target_type || ':' || activity.target_id::text
                            end as item_id
                from raw_activity activity
                join target_access target on target.target_type=activity.target_type
                    and target.target_id=activity.target_id
                join actor_profiles actor_profile on actor_profile.user_id=activity.actor_user_id
                join tbl_follow viewer_actor on viewer_actor.follower_id=:viewerId
                    and viewer_actor.following_id=actor_profile.user_id
                left join tbl_media_asset actor_avatar on actor_avatar.id=actor_profile.avatar_id
                    and actor_avatar.status='READY' and actor_avatar.visibility='PUBLIC'
                where actor_profile.user_id<>:viewerId
                  and not exists(select 1 from tbl_musician_feed_feedback feedback
                      where feedback.viewer_user_id=:viewerId and (
                        (feedback.action in ('HIDE','REPORT') and feedback.item_id=(case
                          when activity.action='COMMENT' then 'ACTIVITY_COMMENT:' || activity.activity_id::text
                          else 'ACTIVITY_LIKE:' || activity.target_type || ':' || activity.target_id::text end))
                        or (feedback.action='MUTE_AUTHOR'
                            and feedback.author_profile_type=actor_profile.profile_type
                            and feedback.author_profile_id=actor_profile.profile_id)))
                  and not exists(select 1 from tbl_musician_feed_delivery delivered
                      where delivered.viewer_user_id=:viewerId and delivered.feed_session_id=:feedSessionId
                        and (delivered.item_id=(case when activity.action='COMMENT'
                              then 'ACTIVITY_COMMENT:' || activity.activity_id::text
                              else 'ACTIVITY_LIKE:' || activity.target_type || ':' || activity.target_id::text end)
                          or (activity.action='LIKE' and delivered.item_type<>'ACTIVITY_COMMENT'
                              and delivered.target_type=activity.target_type
                              and delivered.target_id=activity.target_id)))
            ), ranked as (
                select eligible.*,
                       row_number() over (partition by action, target_type, target_id
                           order by occurred_at desc, activity_id desc) as actor_rank,
                       count(*) over (partition by action, target_type, target_id) as actor_count
                from eligible
            )
            select * from ranked where action='COMMENT' or actor_rank<=:visibleActorLimit
            order by occurred_at desc, activity_id desc
            limit :limit
            """.formatted(EventProfilePublicationRepository.SQL_START_SECONDS,
            EventProfilePublicationRepository.SQL_START_SECONDS);

    private static final String MEDIA_TARGET_SQL = """
            select media.id as target_id, media.kind, media.source_url, media.playback_url,
                   media.thumbnail_url, media.title as media_title, media.description as media_description,
                   media.duration_seconds as media_duration_seconds, media.width, media.height,
                   publication.renderer_type, publication.publication_id, publication.track_title,
                   publication.track_duration_seconds, publication.bpm,
                   (select count(*) from tbl_like likes where likes.target_type='MEDIA'
                       and likes.target_id=media.id) as like_count,
                   (select count(*) from tbl_comment comments where comments.target_type='MEDIA'
                       and comments.target_id=media.id and not comments.is_deleted) as comment_count,
                   exists(select 1 from tbl_like mine where mine.user_id=:viewerId
                       and mine.target_type='MEDIA' and mine.target_id=media.id) as liked_by_me
            from tbl_media_asset media
            join lateral (
                select 'TRACK'::varchar as renderer_type, track.id as publication_id,
                       track.title as track_title, track.duration_seconds as track_duration_seconds,
                       track.bpm, 0 as priority
                from tbl_tracks track
                where :includeTracks and track.media_asset_id=media.id
                  and track.owner_type=media.owner_type and track.owner_id=media.owner_id
                  and track.owner_type in ('MUSICIAN_PROFILE','LISTENER_PROFILE','STUDIO_PROFILE',
                      'VENUE_PROFILE','BAND')
                union all
                select 'PROFILE_MEDIA', attachment.id, null, null, null, 1
                from tbl_profile_media attachment
                where :includeProfileMedia and attachment.media_asset_id=media.id
                  and media.owner_id=attachment.profile_id
                  and media.owner_type=case attachment.profile_type
                      when 'MUSICIAN' then 'MUSICIAN_PROFILE'
                      when 'LISTENER' then 'LISTENER_PROFILE'
                      when 'STUDIO' then 'STUDIO_PROFILE'
                      when 'VENUE' then 'VENUE_PROFILE'
                      when 'BAND' then 'BAND' end
                  and attachment.profile_type in ('MUSICIAN','LISTENER','STUDIO','VENUE','BAND')
                  and attachment.role in ('GALLERY','FEATURED_VIDEO','INTRO_VIDEO')
                order by priority, publication_id limit 1
            ) publication on true
            where media.id in (:targetIds) and media.status='READY' and media.visibility='PUBLIC'
              and coalesce(nullif(trim(media.playback_url),''), nullif(trim(media.source_url),'')) is not null
              and (
                (media.owner_type='MUSICIAN_PROFILE' and exists(select 1 from tbl_musician_profile profile
                    join tbl_user owner_account on owner_account.id=profile.user_id
                      and owner_account.status='ACTIVE' and owner_account.email_verified
                      and owner_account.erased_at is null
                    where profile.id=media.owner_id and owner_account.id<>:viewerId))
                or (media.owner_type='STUDIO_PROFILE' and exists(select 1 from tbl_studio_profile profile
                    join tbl_user owner_account on owner_account.id=profile.user_id
                      and owner_account.status='ACTIVE' and owner_account.email_verified
                      and owner_account.erased_at is null
                    where profile.id=media.owner_id and owner_account.id<>:viewerId))
                or (media.owner_type='LISTENER_PROFILE' and exists(select 1 from \"tbl_listener-profile\" profile
                    join tbl_user owner_account on owner_account.id=profile.user_id
                      and owner_account.status='ACTIVE' and owner_account.email_verified
                      and owner_account.erased_at is null
                    where profile.id=media.owner_id and owner_account.id<>:viewerId
                      and profile.visibility_mode='STANDARD' and profile.visibility_choice_completed
                      and exists(select 1 from user_roles membership join tbl_role role
                          on role.id=membership.role_id where membership.user_id=owner_account.id
                          and role.name='ROLE_LISTENER')
                      and not exists(select 1 from user_roles membership join tbl_role role
                          on role.id=membership.role_id where membership.user_id=owner_account.id
                          and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN','ROLE_VENUE',
                              'ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
                      and not exists(select 1 from tbl_musician_profile p where p.user_id=owner_account.id)
                      and not exists(select 1 from tbl_studio_profile p where p.user_id=owner_account.id)
                      and not exists(select 1 from tbl_organizer_profile p where p.user_id=owner_account.id)
                      and not exists(select 1 from tbl_producer_profile p where p.user_id=owner_account.id)
                      and not exists(select 1 from tbl_venues v where v.owner_id=owner_account.id)))
                or (media.owner_type='VENUE_PROFILE' and exists(select 1 from tbl_venue_profile profile
                    join tbl_venues venue on venue.id=profile.venue_id and venue.status='APPROVED'
                    join tbl_user owner_account on owner_account.id=venue.owner_id
                      and owner_account.status='ACTIVE' and owner_account.email_verified
                      and owner_account.erased_at is null
                    where profile.id=media.owner_id and owner_account.id<>:viewerId))
                or (media.owner_type='BAND'
                    and exists(select 1 from tbl_band_member public_member
                      join tbl_user member_account on member_account.id=public_member.user_id
                        and member_account.status='ACTIVE' and member_account.email_verified
                        and member_account.erased_at is null
                      where public_member.band_id=media.owner_id and public_member.status='ACTIVE')
                    and not exists(select 1 from tbl_band_member own_member where own_member.band_id=media.owner_id
                      and own_member.user_id=:viewerId and own_member.status='ACTIVE')))
            """;

    private static final String EVENT_TARGET_SQL = """
            select event.id as target_id, event.title, event.description, event.event_date,
                   %s as normalized_start_seconds,
                   case when event.end_time is null then null else %s end as normalized_end_seconds,
                   event.event_origin, event.venue_approval_status, event.venue_calendar_approved,
                   coalesce(poster.playback_url, poster.source_url, event.poster_image) as poster_image,
                   venue.id as venue_id, venue.name as venue_name, city.name as venue_city,
                   district.name as venue_district, neighborhood.name as venue_neighborhood,
                   musician.id as musician_profile_id, musician_user.user_name as musician_username,
                   musician.stage_name as musician_stage_name, band.id as band_id, band.name as band_name,
                   event.manual_performer_name,
                   (select count(*) from tbl_like likes where likes.target_type='EVENT'
                       and likes.target_id=event.id) as like_count,
                   (select count(*) from tbl_comment comments where comments.target_type='EVENT'
                       and comments.target_id=event.id and not comments.is_deleted) as comment_count,
                   exists(select 1 from tbl_like mine where mine.user_id=:viewerId
                       and mine.target_type='EVENT' and mine.target_id=event.id) as liked_by_me
            from tbl_event event join tbl_venues venue on venue.id=event.venue_id
            join tbl_user venue_owner on venue_owner.id=venue.owner_id
            join tbl_city city on city.id=venue.city_id
            join tbl_district district on district.id=venue.district_id and district.city_id=city.id
            join tbl_neighborhood neighborhood on neighborhood.id=venue.neighborhood_id
                and neighborhood.district_id=district.id
            left join tbl_musician_profile musician on musician.id=event.musician_profile_id
            left join tbl_user musician_user on musician_user.id=musician.user_id
                and musician_user.status='ACTIVE' and musician_user.email_verified
                and musician_user.erased_at is null
            left join tbl_band band on band.id=event.band_id
            left join tbl_media_asset poster on poster.id::text=event.poster_image
                and poster.status='READY' and poster.visibility='PUBLIC'
            where event.id in (:targetIds) and event.event_origin='VENUE' and event.venue_calendar_approved
              and event.performer_approval_status in ('APPROVED','NOT_REQUIRED')
              and venue.status='APPROVED' and venue_owner.status='ACTIVE'
              and venue_owner.email_verified and venue_owner.erased_at is null
              and event.event_date is not null and event.start_time is not null
              and (event.event_date>:today or (event.event_date=:today and %s>:nowSeconds))
              and not exists(select 1 from event_performer_requests pending
                  where pending.event_id=event.id and pending.status='PENDING')
              and (event.musician_profile_id is null or musician_user.id is not null)
              and (event.band_id is null or exists(select 1 from tbl_band_member public_member
                  join tbl_user member_account on member_account.id=public_member.user_id
                    and member_account.status='ACTIVE' and member_account.email_verified
                    and member_account.erased_at is null
                  where public_member.band_id=event.band_id and public_member.status='ACTIVE'))
              and event.organizer_user_id<>:viewerId
              and not (event.profile_calendar_approved and musician_user.id=:viewerId)
              and not exists(select 1 from tbl_band_member own_member where own_member.band_id=event.band_id
                  and own_member.user_id=:viewerId and own_member.status='ACTIVE')
              and not exists(select 1 from event_member_publications own_publication
                  join tbl_musician_profile own_profile on own_profile.id=own_publication.musician_profile_id
                  where own_publication.event_id=event.id and own_publication.visible
                    and own_profile.user_id=:viewerId)
            """.formatted(EventProfilePublicationRepository.SQL_START_SECONDS,
            EventProfilePublicationRepository.SQL_END_SECONDS,
            EventProfilePublicationRepository.SQL_START_SECONDS);

    private static final String EVENT_POST_TARGET_SQL = """
            select intent.post_id as target_id, intent.note, intent.published_at,
                   event.id as event_id, event.title, event.description, event.event_date,
                   %s as normalized_start_seconds,
                   case when event.end_time is null then null else %s end as normalized_end_seconds,
                   event.event_origin, event.venue_approval_status, event.venue_calendar_approved,
                   coalesce(poster.playback_url, poster.source_url, event.poster_image) as poster_image,
                   venue.id as venue_id, venue.name as venue_name, city.name as venue_city,
                   district.name as venue_district, neighborhood.name as venue_neighborhood,
                   musician.id as musician_profile_id, musician_user.user_name as musician_username,
                   musician.stage_name as musician_stage_name, band.id as band_id, band.name as band_name,
                   event.manual_performer_name,
                   (select count(*) from tbl_like likes where likes.target_type='EVENT_POST'
                       and likes.target_id=intent.post_id) as like_count,
                   (select count(*) from tbl_comment comments where comments.target_type='EVENT_POST'
                       and comments.target_id=intent.post_id and not comments.is_deleted) as comment_count,
                   exists(select 1 from tbl_like mine where mine.user_id=:viewerId
                       and mine.target_type='EVENT_POST' and mine.target_id=intent.post_id) as liked_by_me
            from tbl_event_audience_intent intent join tbl_user publisher on publisher.id=intent.user_id
            join \"tbl_listener-profile\" listener on listener.user_id=publisher.id
                and listener.visibility_mode='STANDARD' and listener.visibility_choice_completed
            join tbl_event event on event.id=intent.event_id
            join tbl_venues venue on venue.id=event.venue_id
            join tbl_user venue_owner on venue_owner.id=venue.owner_id
            join tbl_city city on city.id=venue.city_id
            join tbl_district district on district.id=venue.district_id and district.city_id=city.id
            join tbl_neighborhood neighborhood on neighborhood.id=venue.neighborhood_id
                and neighborhood.district_id=district.id
            left join tbl_musician_profile musician on musician.id=event.musician_profile_id
            left join tbl_user musician_user on musician_user.id=musician.user_id
                and musician_user.status='ACTIVE' and musician_user.email_verified
                and musician_user.erased_at is null
            left join tbl_band band on band.id=event.band_id
            left join tbl_media_asset poster on poster.id::text=event.poster_image
                and poster.status='READY' and poster.visibility='PUBLIC'
            where intent.post_id in (:targetIds) and intent.published_on_profile and intent.intent<>'NONE'
              and intent.published_at<=:anchor
              and publisher.id<>:viewerId and publisher.status='ACTIVE' and publisher.email_verified
              and publisher.erased_at is null
              and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                  where membership.user_id=publisher.id and role.name='ROLE_LISTENER')
              and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                  where membership.user_id=publisher.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                      'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
              and not exists(select 1 from tbl_musician_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_studio_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_producer_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=publisher.id)
              and event.event_origin='VENUE' and event.venue_calendar_approved
              and event.performer_approval_status in ('APPROVED','NOT_REQUIRED')
              and venue.status='APPROVED' and venue_owner.status='ACTIVE'
              and venue_owner.email_verified and venue_owner.erased_at is null
              and event.event_date is not null and event.start_time is not null
              and (event.event_date>:today or (event.event_date=:today and %s>:nowSeconds))
              and not exists(select 1 from event_performer_requests pending
                  where pending.event_id=event.id and pending.status='PENDING')
              and (event.musician_profile_id is null or musician_user.id is not null)
              and (event.band_id is null or exists(select 1 from tbl_band_member public_member
                  join tbl_user member_account on member_account.id=public_member.user_id
                    and member_account.status='ACTIVE' and member_account.email_verified
                    and member_account.erased_at is null
                  where public_member.band_id=event.band_id and public_member.status='ACTIVE'))
            """.formatted(EventProfilePublicationRepository.SQL_START_SECONDS,
            EventProfilePublicationRepository.SQL_END_SECONDS,
            EventProfilePublicationRepository.SQL_START_SECONDS);

    private static final String TABLE_TARGET_SQL = """
            select share.id as target_id, share.note, share.published_at, share.final_source::text as final_source,
                   table_group.id as source_id, table_group.description, table_group.venue_name,
                   city.name as city_name, district.name as district_name, table_group.meeting_at,
                   table_group.expires_at, table_group.status, table_group.max_person_count,
                   (select count(*) from tbl_table_group_participants participant
                       where participant.table_group_id=table_group.id and participant.status='ACCEPTED') as accepted_count,
                   (select count(*) from tbl_like likes where likes.target_type='TABLE_GROUP_POST'
                       and likes.target_id=share.id) as like_count,
                   (select count(*) from tbl_comment comments where comments.target_type='TABLE_GROUP_POST'
                       and comments.target_id=share.id and not comments.is_deleted) as comment_count,
                   exists(select 1 from tbl_like mine where mine.user_id=:viewerId
                       and mine.target_type='TABLE_GROUP_POST' and mine.target_id=share.id) as liked_by_me
            from tbl_table_group_profile_share share join tbl_user publisher on publisher.id=share.owner_user_id
            join \"tbl_listener-profile\" listener on listener.id=share.listener_profile_id
                and listener.user_id=publisher.id and listener.visibility_mode='STANDARD'
                and listener.visibility_choice_completed
            join tbl_table_group table_group on table_group.id=share.table_group_id
            join tbl_city city on city.id=table_group.city_id
            left join tbl_district district on district.id=table_group.district_id
            where share.id in (:targetIds) and share.published_at<=:anchor and publisher.id<>:viewerId
              and publisher.status='ACTIVE' and publisher.email_verified and publisher.erased_at is null
              and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                  where membership.user_id=publisher.id and role.name='ROLE_LISTENER')
              and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                  where membership.user_id=publisher.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                      'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
              and not exists(select 1 from tbl_musician_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_studio_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_producer_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=publisher.id)
              and (share.final_source is not null or (not share.final_source_frozen
                  and table_group.status='ACTIVE' and table_group.expires_at>:readAt
                  and (table_group.owner_id=share.owner_user_id or exists (
                    select 1 from tbl_table_group_participants eligible
                    where eligible.table_group_id=table_group.id
                      and eligible.user_id=share.owner_user_id and eligible.status='ACCEPTED'))))
            """;

    private static final String OVERTHINKING_TARGET_SQL = """
            select share.id as target_id, share.note, share.published_at, share.source_post_id as source_id,
                   (select count(*) from tbl_like likes where likes.target_type='OVERTHINKING_PROFILE_SHARE'
                       and likes.target_id=share.id) as like_count,
                   (select count(*) from tbl_comment comments where comments.target_type='OVERTHINKING_PROFILE_SHARE'
                       and comments.target_id=share.id and not comments.is_deleted) as comment_count,
                   exists(select 1 from tbl_like mine where mine.user_id=:viewerId
                       and mine.target_type='OVERTHINKING_PROFILE_SHARE' and mine.target_id=share.id) as liked_by_me
            from tbl_overthinking_profile_share share join tbl_user publisher on publisher.id=share.owner_user_id
            join \"tbl_listener-profile\" listener on listener.id=share.listener_profile_id
                and listener.user_id=publisher.id and listener.visibility_mode='STANDARD'
                and listener.visibility_choice_completed
            join tbl_overthinking_post source on source.id=share.source_post_id
            where share.id in (:targetIds) and share.published_at<=:anchor and publisher.id<>:viewerId
              and publisher.status='ACTIVE' and publisher.email_verified and publisher.erased_at is null
              and exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                  where membership.user_id=publisher.id and role.name='ROLE_LISTENER')
              and not exists(select 1 from user_roles membership join tbl_role role on role.id=membership.role_id
                  where membership.user_id=publisher.id and role.name in ('ROLE_ADMIN','ROLE_OWNER','ROLE_MUSICIAN',
                      'ROLE_VENUE','ROLE_STUDIO','ROLE_ORGANIZER','ROLE_PRODUCER'))
              and not exists(select 1 from tbl_musician_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_studio_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_organizer_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_producer_profile profile where profile.user_id=publisher.id)
              and not exists(select 1 from tbl_venues owned_venue where owned_venue.owner_id=publisher.id)
            """;

    private final NamedParameterJdbcTemplate jdbc;
    private final EventShareUrlBuilder shareUrls;
    private final ObjectMapper objectMapper;
    private final OverthinkingPostService overthinkingPosts;

    public MusicianFeedMediaActivityCandidateProvider(
            NamedParameterJdbcTemplate jdbc,
            EventShareUrlBuilder shareUrls,
            ObjectMapper objectMapper,
            OverthinkingPostService overthinkingPosts
    ) {
        this.jdbc = jdbc;
        this.shareUrls = shareUrls;
        this.objectMapper = objectMapper;
        this.overthinkingPosts = overthinkingPosts;
    }

    @Override public String providerId() { return "followed-user-social-activity"; }
    @Override public Set<MusicianFeedItemType> supportedTypes() {
        return Set.of(MusicianFeedItemType.ACTIVITY_LIKE, MusicianFeedItemType.ACTIVITY_COMMENT);
    }

    @Override
    @Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW, timeout = 5)
    public List<MusicianFeedCandidate> findCandidates(MusicianFeedCandidateRequest request) {
        boolean likes = request.supportedTypes().contains(MusicianFeedItemType.ACTIVITY_LIKE);
        boolean comments = request.supportedTypes().contains(MusicianFeedItemType.ACTIVITY_COMMENT);
        if (!likes && !comments) return List.of();

        EnumSet<ActivityTarget> renderers = supportedTargets(request.supportedTypes());
        if (renderers.isEmpty()) return List.of();
        ZonedDateTime now = request.readAt().atZone(EVENT_ZONE);
        var parameters = baseParameters(request, now)
                .addValue("includeLikes", likes).addValue("includeComments", comments)
                .addValue("includeMedia", renderers.contains(ActivityTarget.MEDIA))
                .addValue("includeTracks", request.supportedTypes().contains(MusicianFeedItemType.TRACK))
                .addValue("includeProfileMedia", request.supportedTypes().contains(MusicianFeedItemType.PROFILE_MEDIA))
                .addValue("includeEvents", renderers.contains(ActivityTarget.EVENT))
                .addValue("includeEventPosts", renderers.contains(ActivityTarget.EVENT_POST))
                .addValue("includeTablePosts", renderers.contains(ActivityTarget.TABLE_GROUP_POST))
                .addValue("includeOverthinkingPosts", renderers.contains(ActivityTarget.OVERTHINKING_PROFILE_SHARE))
                .addValue("targetTypes", renderers.stream().map(ActivityTarget::databaseType).toList())
                .addValue("visibleActorLimit", MAX_VISIBLE_ACTORS)
                .addValue("limit", request.limit());
        List<ActivityRow> rows = jdbc.query(ACTIVITY_SQL, parameters, this::activityRow);
        if (rows.isEmpty()) return List.of();

        Map<TargetKey, TargetProjection> targets = hydrateTargets(request, now, rows);
        Map<String, LikeGroup> likesByTarget = new LinkedHashMap<>();
        List<MusicianFeedCandidate> result = new ArrayList<>();
        for (ActivityRow row : rows) {
            TargetProjection projection = targets.get(new TargetKey(row.targetType(), row.targetId()));
            if (projection == null) continue;
            if ("COMMENT".equals(row.action())) {
                result.add(candidate(row.itemId(), MusicianFeedItemType.ACTIVITY_COMMENT, row.occurredAt(),
                        row.actor(), List.of(row.actor()), 0, projection,
                        MusicianFeedReasonCode.FOLLOWED_USER_COMMENTED, 900_000L));
            } else {
                likesByTarget.computeIfAbsent(row.itemId(), ignored -> new LikeGroup(row, projection)).add(row);
            }
        }
        likesByTarget.values().stream().map(LikeGroup::candidate).forEach(result::add);
        result.sort(Comparator.comparing(MusicianFeedCandidate::occurredAt).reversed()
                .thenComparing(MusicianFeedCandidate::itemId));
        return List.copyOf(result.stream().limit(request.limit()).toList());
    }

    private MapSqlParameterSource baseParameters(MusicianFeedCandidateRequest request, ZonedDateTime now) {
        return new MapSqlParameterSource().addValue("viewerId", request.viewerUserId())
                .addValue("feedSessionId", request.feedSessionId())
                .addValue("anchor", MusicianFeedJdbcSupport.timestamp(request.anchor()))
                .addValue("readAt", MusicianFeedJdbcSupport.timestamp(request.readAt()))
                .addValue("today", now.toLocalDate()).addValue("nowSeconds", now.toLocalTime().toSecondOfDay())
                .addValue("storageMidnight", MusicianFeedJdbcSupport.hibernateUtcStorageTime(LocalTime.MIDNIGHT));
    }

    private EnumSet<ActivityTarget> supportedTargets(Set<MusicianFeedItemType> types) {
        EnumSet<ActivityTarget> result = EnumSet.noneOf(ActivityTarget.class);
        if (types.contains(MusicianFeedItemType.TRACK) || types.contains(MusicianFeedItemType.PROFILE_MEDIA)) {
            result.add(ActivityTarget.MEDIA);
        }
        if (types.contains(MusicianFeedItemType.EVENT)) result.add(ActivityTarget.EVENT);
        if (types.contains(MusicianFeedItemType.EVENT_PROFILE_SHARE)) result.add(ActivityTarget.EVENT_POST);
        if (types.contains(MusicianFeedItemType.TABLEGROUP_PROFILE_SHARE)) result.add(ActivityTarget.TABLE_GROUP_POST);
        if (types.contains(MusicianFeedItemType.OVERTHINKING_PROFILE_SHARE)) {
            result.add(ActivityTarget.OVERTHINKING_PROFILE_SHARE);
        }
        return result;
    }

    private ActivityRow activityRow(ResultSet row, int index) throws SQLException {
        var actor = new MusicianFeedItemResponse.Author(
                MusicianFeedJdbcSupport.uuid(row, "actor_user_id"),
                MusicianFeedJdbcSupport.uuid(row, "actor_profile_id"), row.getString("actor_profile_type"),
                row.getString("actor_username"), row.getString("actor_display_name"),
                row.getString("actor_avatar_url"), true);
        return new ActivityRow(row.getString("item_id"), row.getString("action"),
                row.getString("target_type"), MusicianFeedJdbcSupport.uuid(row, "target_id"),
                MusicianFeedJdbcSupport.instant(row, "occurred_at"), actor, row.getLong("actor_count"));
    }

    private Map<TargetKey, TargetProjection> hydrateTargets(
            MusicianFeedCandidateRequest request,
            ZonedDateTime now,
            Collection<ActivityRow> rows
    ) {
        Map<String, LinkedHashSet<UUID>> ids = new LinkedHashMap<>();
        for (ActivityRow row : rows) ids.computeIfAbsent(row.targetType(), ignored -> new LinkedHashSet<>())
                .add(row.targetId());
        Map<TargetKey, TargetProjection> result = new LinkedHashMap<>();
        var base = baseParameters(request, now)
                .addValue("includeTracks", request.supportedTypes().contains(MusicianFeedItemType.TRACK))
                .addValue("includeProfileMedia", request.supportedTypes().contains(MusicianFeedItemType.PROFILE_MEDIA));
        query(ids, ActivityTarget.MEDIA, MEDIA_TARGET_SQL, base, this::mediaTarget, result);
        query(ids, ActivityTarget.EVENT, EVENT_TARGET_SQL, base, this::eventTarget, result);
        query(ids, ActivityTarget.EVENT_POST, EVENT_POST_TARGET_SQL, base, this::eventPostTarget, result);
        query(ids, ActivityTarget.TABLE_GROUP_POST, TABLE_TARGET_SQL, base, this::tableTarget, result);

        LinkedHashSet<UUID> overthinkingIds = ids.get(ActivityTarget.OVERTHINKING_PROFILE_SHARE.databaseType());
        if (overthinkingIds != null && !overthinkingIds.isEmpty()) {
            List<OverthinkingTargetRow> sourceRows = jdbc.query(OVERTHINKING_TARGET_SQL,
                    copy(base).addValue("targetIds", List.copyOf(overthinkingIds)), this::overthinkingTargetRow);
            Map<UUID, OverthinkingPostResponseDto> sources = MusicianFeedOverthinkingSources.resolve(
                    overthinkingPosts, request.viewerUserId(), sourceRows.stream()
                            .map(OverthinkingTargetRow::sourceId).toList());
            for (OverthinkingTargetRow row : sourceRows) {
                OverthinkingPostResponseDto source = sources.get(row.sourceId());
                if (source == null) continue;
                var payload = new MusicianFeedPayloads.ProfileShare(row.targetId(), row.note(),
                        row.publishedAt(), source);
                result.put(new TargetKey(ActivityTarget.OVERTHINKING_PROFILE_SHARE.databaseType(), row.targetId()),
                        new TargetProjection(MusicianFeedItemType.OVERTHINKING_PROFILE_SHARE, payload,
                                row.engagement()));
            }
        }
        return Map.copyOf(result);
    }

    private void query(
            Map<String, LinkedHashSet<UUID>> ids,
            ActivityTarget type,
            String sql,
            MapSqlParameterSource parameters,
            org.springframework.jdbc.core.RowMapper<TargetProjection> mapper,
            Map<TargetKey, TargetProjection> output
    ) {
        LinkedHashSet<UUID> targetIds = ids.get(type.databaseType());
        if (targetIds == null || targetIds.isEmpty()) return;
        for (TargetProjection value : jdbc.query(sql,
                copy(parameters).addValue("targetIds", List.copyOf(targetIds)), mapper)) {
            output.put(new TargetKey(type.databaseType(), value.engagement().targetId()), value);
        }
    }

    private MapSqlParameterSource copy(MapSqlParameterSource source) {
        MapSqlParameterSource result = new MapSqlParameterSource();
        for (String name : source.getParameterNames()) result.addValue(name, source.getValue(name));
        return result;
    }

    private TargetProjection mediaTarget(ResultSet row, int index) throws SQLException {
        UUID mediaId = MusicianFeedJdbcSupport.uuid(row, "target_id");
        MusicianFeedItemType itemType;
        Object payload;
        if ("TRACK".equals(row.getString("renderer_type"))) {
            itemType = MusicianFeedItemType.TRACK;
            payload = new MusicianFeedPayloads.Track(MusicianFeedJdbcSupport.uuid(row, "publication_id"), mediaId,
                    row.getString("track_title"), firstText(row.getString("playback_url"), row.getString("source_url")),
                    (Integer) row.getObject("track_duration_seconds"), (Integer) row.getObject("bpm"));
        } else {
            itemType = MusicianFeedItemType.PROFILE_MEDIA;
            String kind = row.getString("kind");
            String source = row.getString("source_url");
            String playback = row.getString("playback_url");
            String display = "IMAGE".equals(kind) ? source
                    : firstText(row.getString("thumbnail_url"), playback, source);
            payload = new MusicianFeedPayloads.ProfileMedia(mediaId, kind, display,
                    firstText(playback, source), row.getString("thumbnail_url"), row.getString("media_title"),
                    row.getString("media_description"), (Integer) row.getObject("media_duration_seconds"),
                    (Integer) row.getObject("width"), (Integer) row.getObject("height"));
        }
        return new TargetProjection(itemType, payload,
                MusicianFeedJdbcSupport.engagement(row, "MEDIA", mediaId));
    }

    private TargetProjection eventTarget(ResultSet row, int index) throws SQLException {
        UUID eventId = MusicianFeedJdbcSupport.uuid(row, "target_id");
        return new TargetProjection(MusicianFeedItemType.EVENT,
                new MusicianFeedPayloads.Event(event(row, eventId), null, null),
                MusicianFeedJdbcSupport.engagement(row, "EVENT", eventId));
    }

    private TargetProjection eventPostTarget(ResultSet row, int index) throws SQLException {
        UUID postId = MusicianFeedJdbcSupport.uuid(row, "target_id");
        UUID eventId = MusicianFeedJdbcSupport.uuid(row, "event_id");
        return new TargetProjection(MusicianFeedItemType.EVENT_PROFILE_SHARE,
                new MusicianFeedPayloads.Event(event(row, eventId), row.getString("note"), postId),
                MusicianFeedJdbcSupport.engagement(row, "EVENT_POST", postId));
    }

    private TargetProjection tableTarget(ResultSet row, int index) throws SQLException {
        UUID shareId = MusicianFeedJdbcSupport.uuid(row, "target_id");
        TableGroupProfileShareResponse.Source source;
        String frozen = row.getString("final_source");
        if (frozen != null && !frozen.isBlank()) {
            try {
                source = objectMapper.readValue(frozen, TableGroupProfileShareResponse.Source.class);
            } catch (JsonProcessingException invalidSnapshot) {
                throw new SQLException("Invalid frozen TableGroup public snapshot", invalidSnapshot);
            }
        } else {
            source = new TableGroupProfileShareResponse.Source(
                    MusicianFeedJdbcSupport.uuid(row, "source_id"), row.getString("description"),
                    row.getString("venue_name"), row.getString("city_name"), row.getString("district_name"),
                    MusicianFeedJdbcSupport.instant(row, "meeting_at"),
                    MusicianFeedJdbcSupport.instant(row, "expires_at"),
                    TableGroupStatus.valueOf(row.getString("status")), row.getInt("max_person_count"),
                    row.getLong("accepted_count"));
        }
        var payload = new MusicianFeedPayloads.ProfileShare(shareId, row.getString("note"),
                MusicianFeedJdbcSupport.instant(row, "published_at"), source);
        return new TargetProjection(MusicianFeedItemType.TABLEGROUP_PROFILE_SHARE, payload,
                MusicianFeedJdbcSupport.engagement(row, "TABLE_GROUP_POST", shareId));
    }

    private OverthinkingTargetRow overthinkingTargetRow(ResultSet row, int index) throws SQLException {
        UUID targetId = MusicianFeedJdbcSupport.uuid(row, "target_id");
        return new OverthinkingTargetRow(targetId, MusicianFeedJdbcSupport.uuid(row, "source_id"),
                row.getString("note"), MusicianFeedJdbcSupport.instant(row, "published_at"),
                MusicianFeedJdbcSupport.engagement(row, "OVERTHINKING_PROFILE_SHARE", targetId));
    }

    private EventResponseDto event(ResultSet row, UUID eventId) throws SQLException {
        UUID musicianId = MusicianFeedJdbcSupport.uuid(row, "musician_profile_id");
        UUID bandId = MusicianFeedJdbcSupport.uuid(row, "band_id");
        String manualName = row.getString("manual_performer_name");
        PerformerType performerType = bandId != null ? PerformerType.BAND
                : musicianId != null ? PerformerType.MUSICIAN
                : manualName != null && !manualName.isBlank() ? PerformerType.MANUAL : null;
        String performerName = bandId != null ? row.getString("band_name")
                : musicianId != null ? firstText(row.getString("musician_stage_name"),
                row.getString("musician_username")) : firstText(manualName, "Belirtilmemiş");
        return new EventResponseDto(eventId, row.getString("title"), row.getString("poster_image"),
                performerName, musicianId, bandId, performerType, Set.of(),
                MusicianFeedJdbcSupport.uuid(row, "venue_id"), row.getString("venue_name"),
                row.getString("venue_city"), row.getString("venue_district"),
                row.getString("venue_neighborhood"), row.getObject("event_date", LocalDate.class),
                MusicianFeedJdbcSupport.normalizedTime(row, "normalized_start_seconds"),
                MusicianFeedJdbcSupport.normalizedTime(row, "normalized_end_seconds"),
                row.getString("description"), shareUrls.buildEventShareUrl(eventId),
                EventOrigin.valueOf(row.getString("event_origin")),
                EventVenueApprovalStatus.valueOf(row.getString("venue_approval_status")),
                row.getBoolean("venue_calendar_approved"));
    }

    private MusicianFeedCandidate candidate(
            String itemId,
            MusicianFeedItemType type,
            Instant occurredAt,
            MusicianFeedItemResponse.Author actor,
            List<MusicianFeedItemResponse.Author> actors,
            int secondaryActorCount,
            TargetProjection target,
            MusicianFeedReasonCode reasonCode,
            long score
    ) {
        String action = type == MusicianFeedItemType.ACTIVITY_COMMENT ? "COMMENT" : "LIKE";
        var payload = new MusicianFeedPayloads.Activity(action, actor,
                target.itemType(), target.payload());
        String targetType = target.engagement().targetType();
        MusicianFeedLane lane = "TABLE_GROUP_POST".equals(targetType)
                || "OVERTHINKING_PROFILE_SHARE".equals(targetType)
                ? MusicianFeedLane.MODULE_SHARE : MusicianFeedLane.FOLLOWING;
        return new MusicianFeedCandidate(itemId, type, 1, occurredAt,
                new MusicianFeedItemResponse.Reason(reasonCode, actors, secondaryActorCount), actor,
                new MusicianFeedItemResponse.Target(target.engagement().targetType(),
                        target.engagement().targetId()),
                target.engagement(), null, MusicianFeedJdbcSupport.standardFeedback(), payload,
                score, 0, lane, false);
    }

    private static String firstText(String... values) {
        return Arrays.stream(values).filter(value -> value != null && !value.isBlank()).findFirst().orElse(null);
    }

    private enum ActivityTarget {
        MEDIA("MEDIA"), EVENT("EVENT"), EVENT_POST("EVENT_POST"),
        TABLE_GROUP_POST("TABLE_GROUP_POST"), OVERTHINKING_PROFILE_SHARE("OVERTHINKING_PROFILE_SHARE");

        private final String databaseType;
        ActivityTarget(String databaseType) { this.databaseType = databaseType; }
        String databaseType() { return databaseType; }
    }

    private record ActivityRow(
            String itemId,
            String action,
            String targetType,
            UUID targetId,
            Instant occurredAt,
            MusicianFeedItemResponse.Author actor,
            long actorCount
    ) { }

    private record TargetKey(String type, UUID id) { }
    private record TargetProjection(MusicianFeedItemType itemType, Object payload,
                                    MusicianFeedItemResponse.Engagement engagement) { }
    private record OverthinkingTargetRow(UUID targetId, UUID sourceId, String note, Instant publishedAt,
                                         MusicianFeedItemResponse.Engagement engagement) { }

    private final class LikeGroup {
        private final ActivityRow primary;
        private final TargetProjection target;
        private final LinkedHashMap<String, MusicianFeedItemResponse.Author> actors = new LinkedHashMap<>();
        private long actorCount;

        private LikeGroup(ActivityRow primary, TargetProjection target) {
            this.primary = primary;
            this.target = target;
        }

        private void add(ActivityRow row) {
            actorCount = Math.max(actorCount, row.actorCount());
            actors.putIfAbsent(row.actor().profileType() + ":" + row.actor().profileId(), row.actor());
        }

        private MusicianFeedCandidate candidate() {
            List<MusicianFeedItemResponse.Author> visible = actors.values().stream()
                    .limit(MAX_VISIBLE_ACTORS).toList();
            return MusicianFeedMediaActivityCandidateProvider.this.candidate(primary.itemId(),
                    MusicianFeedItemType.ACTIVITY_LIKE, primary.occurredAt(), visible.getFirst(), visible,
                    secondaryCount(actorCount, visible.size()), target,
                    MusicianFeedReasonCode.FOLLOWED_USER_LIKED, 820_000L);
        }
    }

    private static int secondaryCount(long total, int visible) {
        return (int) Math.min(Integer.MAX_VALUE, Math.max(0L, total - visible));
    }
}
