package com.berkayb.soundconnect.modules.role.enums;

public enum PermissionEnum {
	// CORE ADMIN
	ADMIN_PANEL_ACCESS,
	MANAGE_ROLES,
	MANAGE_PERMISSIONS,
	READ_USERS,
	MANAGE_USERS,
	MANAGE_LOCATIONS,
	MANAGE_VENUE_APPLICATIONS,
	MANAGE_VENUES,
	MANAGE_PROMOTIONS,
	MANAGE_INSTRUMENTS,
	MANAGE_PROFILES,
	MANAGE_DM,
	
	// USER
	READ_USER, // sisteme kayit olan herkes bu role sahip olur.
	
	WRITE_USER,
	DELETE_USER,
	READ_ALL_USERS,
	
	// ROLE
	READ_ROLE,
	WRITE_ROLE,
	DELETE_ROLE,
	
	// PERMISSION işlemleri yetkisi
	READ_PERMISSION,
	WRITE_PERMISSION,
	DELETE_PERMISSION,
	
	// VENUE
	READ_VENUE, // mekan sahipleri icin
	WRITE_VENUE,
	DELETE_VENUE,
	ASSIGN_ARTIST_TO_VENUE, // mekan sahipleri icin
	
	// LOCATION
	READ_LOCATION,
	WRITE_LOCATION,
	DELETE_LOCATION,
	
	// COMMENT
	DELETE_COMMENT
	
}
