package com.berkayb.soundconnect.tools.simulation.world;

import java.util.List;

/**
 * Version-controlled, deterministic description of the local simulation world.
 *
 * <p>The manifest deliberately stores stable logical keys and catalog names rather than database
 * identifiers. Location identifiers are generated by the catalog seeder and therefore must be
 * resolved by name when a world is materialized.</p>
 */
public record SimulationWorldManifest(
		int schemaVersion,
		String worldId,
		long seed,
		List<ScenePlan> scenes,
		ContentTargets contentTargets,
		List<Account> accounts,
		List<Band> bands
) {
	public SimulationWorldManifest {
		scenes = immutable(scenes);
		accounts = immutable(accounts);
		bands = immutable(bands);
	}

	private static <T> List<T> immutable(List<T> values) {
		return values == null ? List.of() : List.copyOf(values);
	}

	public enum AccountRole {
		MUSICIAN,
		LISTENER,
		VENUE,
		STUDIO
	}

	public enum EmailVerificationState {
		VERIFIED,
		UNVERIFIED
	}

	public enum Scene {
		ISTANBUL_ALTERNATIVE_ROCK,
		ANKARA_POP_ELECTRONIC,
		IZMIR_JAZZ_FUNK,
		BURSA_METAL_ACOUSTIC,
		ANTALYA_ESKISEHIR_BRIDGES
	}

	public enum ObserverProfile {
		NONE,
		COMPLETE,
		INCOMPLETE,
		COLD_START
	}

	public enum ListenerVisibilityState {
		STANDARD,
		GHOST,
		VISIBILITY_PENDING
	}

	public enum InstitutionState {
		APPROVED,
		PENDING,
		REJECTED
	}

	public enum BandMemberRole {
		FOUNDER,
		MANAGER,
		MEMBER
	}

	public record ScenePlan(
			Scene scene,
			List<String> cityFocus,
			int musicians,
			int listeners,
			int venues,
			int studios,
			int bands
	) {
		public ScenePlan {
			cityFocus = immutable(cityFocus);
		}
	}

	public record ContentTargets(
			int collabListings,
			int events,
			int tracks,
			int profileMediaPublications,
			int overthinkingProfileShares,
			int tableGroupProfileShares,
			int listenerEventProfilePublications,
			int follows,
			int likes,
			int comments
	) {
	}

	public record Account(
			String key,
			AccountRole role,
			Scene scene,
			String username,
			String email,
			EmailVerificationState emailVerification,
			String givenName,
			String familyName,
			String displayName,
			String bio,
			String archetype,
			List<String> instrumentNames,
			MusicianProfilePlan musicianProfile,
			ObserverProfile observer,
			ListenerVisibilityState listenerVisibility,
			InstitutionState institutionState,
			Location location,
			String contactPhone
	) {
		public Account {
			instrumentNames = immutable(instrumentNames);
		}
	}

	public record MusicianProfilePlan(
			boolean populateBio,
			boolean populateLocation,
			boolean populateInstruments,
			boolean populateProfilePhoto,
			boolean populatePortfolio,
			boolean populateSocialLinks
	) {
		public boolean isComplete() {
			return populateBio && populateLocation && populateInstruments && populateProfilePhoto
					&& populatePortfolio && populateSocialLinks;
		}
	}

	public record Location(
			String city,
			String district,
			String neighborhood,
			String addressLine
	) {
	}

	public record Band(
			String key,
			String name,
			String bio,
			String archetype,
			Scene scene,
			String ownerAccountKey,
			List<BandMember> members
	) {
		public Band {
			members = immutable(members);
		}
	}

	public record BandMember(
			String accountKey,
			BandMemberRole role
	) {
	}
}
