[CmdletBinding()]
param(
    [ValidateSet("up", "idea", "infra", "boot", "down", "logs", "ps", "config", "reset-local")]
    [string]$Action = "up",

    [string]$Service,

    [switch]$Force
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $ProjectRoot ".env.local"
$EnvTemplate = Join-Path $ProjectRoot ".env.example"
$WorkerDbEnvFile = Join-Path $ProjectRoot ".env.worker-db.local"
$WorkerRabbitEnvFile = Join-Path $ProjectRoot ".env.worker-rabbit.local"
$StudioSchemaPath = Join-Path $ProjectRoot "scripts\db\2026-07-21-studio-domain.sql"

function Assert-Command([string]$Name) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command '$Name' was not found on PATH."
    }
}

function Assert-LocalEnv {
    if (Test-Path -LiteralPath $EnvFile) {
        return
    }

    Copy-Item -LiteralPath $EnvTemplate -Destination $EnvFile
    Write-Host "Created .env.local from .env.example." -ForegroundColor Yellow
    Write-Host "Fill in the real local secrets, then run this command again." -ForegroundColor Yellow
    exit 2
}

function Read-DotEnvMap([string]$Path) {
    $Values = @{}
    foreach ($Line in Get-Content -LiteralPath $Path) {
        $Trimmed = $Line.Trim()
        if (-not $Trimmed -or $Trimmed.StartsWith("#")) {
            continue
        }

        $Pair = $Trimmed.Split("=", 2)
        if ($Pair.Count -ne 2 -or -not $Pair[0].Trim()) {
            throw "Invalid entry in ${Path}: $Line"
        }

        $Key = $Pair[0].Trim()
        if ($Values.ContainsKey($Key)) {
            throw "Duplicate key '$Key' in $Path"
        }

        $Value = $Pair[1].Trim()
        if ($Value.Length -ge 2 -and (($Value.StartsWith('"') -and $Value.EndsWith('"')) -or ($Value.StartsWith("'") -and $Value.EndsWith("'")))) {
            $Value = $Value.Substring(1, $Value.Length - 2)
        }
        $Values[$Key] = $Value
    }
    return $Values
}

function New-RandomHexSecret {
    $Bytes = New-Object byte[] 32
    $Generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $Generator.GetBytes($Bytes)
    }
    finally {
        $Generator.Dispose()
    }
    return -join ($Bytes | ForEach-Object { $_.ToString("x2") })
}

function New-WorkerCredentialFile(
    [string]$Path,
    [string]$Description,
    [string]$UsernameKey,
    [string]$Username,
    [string]$PasswordKey
) {
    $Secret = New-RandomHexSecret
    $Lines = @(
        "# Generated by scripts/dev.ps1. Local only; never commit this file.",
        "${UsernameKey}=${Username}",
        "${PasswordKey}=${Secret}"
    )
    $Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($Path, $Lines, $Utf8NoBom)
    Write-Host "Generated isolated $Description credentials." -ForegroundColor Green
}

function Assert-WorkerCredentialFile(
    [string]$Path,
    [string]$Description,
    [string]$UsernameKey,
    [string]$PasswordKey,
    [string]$UsernamePattern
) {
    $Values = Read-DotEnvMap $Path
    $AllowedKeys = @($UsernameKey, $PasswordKey)
    $UnexpectedKeys = @($Values.Keys | Where-Object { $_ -notin $AllowedKeys })
    if ($UnexpectedKeys) {
        throw "$Description credential file contains unsupported keys: $($UnexpectedKeys -join ', ')"
    }

    $Username = $Values[$UsernameKey]
    $Password = $Values[$PasswordKey]
    if ([string]::IsNullOrWhiteSpace($Username) -or $Username -notmatch $UsernamePattern) {
        throw "$Description username is missing or contains unsupported characters."
    }
    if ([string]::IsNullOrWhiteSpace($Password) -or $Password.Length -lt 48 -or $Password -notmatch '^[A-Za-z0-9._~-]+$') {
        throw "$Description password must be an independently generated URL-safe secret of at least 48 characters."
    }
}

function Initialize-WorkerCredentials {
    if (-not (Test-Path -LiteralPath $WorkerDbEnvFile)) {
        New-WorkerCredentialFile `
            -Path $WorkerDbEnvFile `
            -Description "media-worker PostgreSQL" `
            -UsernameKey "SOUNDCONNECT_MEDIA_WORKER_POSTGRES_USERNAME" `
            -Username "soundconnect_media_worker" `
            -PasswordKey "SOUNDCONNECT_MEDIA_WORKER_POSTGRES_PASSWORD"
    }
    if (-not (Test-Path -LiteralPath $WorkerRabbitEnvFile)) {
        New-WorkerCredentialFile `
            -Path $WorkerRabbitEnvFile `
            -Description "media-worker RabbitMQ" `
            -UsernameKey "SOUNDCONNECT_MEDIA_WORKER_RABBITMQ_USERNAME" `
            -Username "soundconnect-media-worker" `
            -PasswordKey "SOUNDCONNECT_MEDIA_WORKER_RABBITMQ_PASSWORD"
    }

    Assert-WorkerCredentialFile `
        -Path $WorkerDbEnvFile `
        -Description "media-worker PostgreSQL" `
        -UsernameKey "SOUNDCONNECT_MEDIA_WORKER_POSTGRES_USERNAME" `
        -PasswordKey "SOUNDCONNECT_MEDIA_WORKER_POSTGRES_PASSWORD" `
        -UsernamePattern '^[A-Za-z0-9_-]+$'
    Assert-WorkerCredentialFile `
        -Path $WorkerRabbitEnvFile `
        -Description "media-worker RabbitMQ" `
        -UsernameKey "SOUNDCONNECT_MEDIA_WORKER_RABBITMQ_USERNAME" `
        -PasswordKey "SOUNDCONNECT_MEDIA_WORKER_RABBITMQ_PASSWORD" `
        -UsernamePattern '^[A-Za-z0-9._-]+$'
}

function Assert-ApiEnvironmentBoundary {
    $Values = Read-DotEnvMap $EnvFile
    $WorkerKeys = @($Values.Keys | Where-Object { $_ -like 'SOUNDCONNECT_MEDIA_WORKER_*' })
    if ($WorkerKeys) {
        throw ".env.local is API-only and must not contain media-worker variables. Use the generated .env.worker-*.local files."
    }
}

function Assert-NoPlaceholders {
    $RequiredKeys = @(
        "SOUNDCONNECT_POSTGRES_PASSWORD",
        "SOUNDCONNECT_JWT_SECRETKEY",
        "SPRING_RABBITMQ_PASSWORD",
        "MAILERSEND_API_KEY",
        "MAILERSEND_SENDER_EMAIL",
        "SPOTIFY_CLIENT_ID",
        "SPOTIFY_CLIENT_SECRET"
    )

    $PlaceholderKeys = foreach ($Line in Get-Content -LiteralPath $EnvFile) {
        $Trimmed = $Line.Trim()
        if (-not $Trimmed -or $Trimmed.StartsWith("#")) {
            continue
        }

        $Pair = $Trimmed.Split("=", 2)
        if ($Pair.Count -ne 2) {
            continue
        }

        $Value = $Pair[1].Trim().Trim('"').Trim("'")
        $Key = $Pair[0].Trim()
        if ($Key -in $RequiredKeys -and ($Value -match "^(change-me|replace-me(?:$|\..*)|replace-with-.+)$" -or $Value -match "example\.com")) {
            $Key
        }
    }

    if ($PlaceholderKeys) {
        $Names = ($PlaceholderKeys | Sort-Object -Unique) -join ", "
        throw "Replace placeholder values in .env.local before startup: $Names"
    }
}

function Invoke-Compose([string[]]$Arguments) {
    & docker compose --project-directory $ProjectRoot --env-file $EnvFile @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed with exit code $LASTEXITCODE."
    }
}

function Get-LocalPostgresConnection {
    $Values = Read-DotEnvMap $EnvFile
    return @{
        Username = if ($Values["SOUNDCONNECT_POSTGRES_USERNAME"]) { $Values["SOUNDCONNECT_POSTGRES_USERNAME"] } else { "soundconnect" }
        Database = if ($Values["SOUNDCONNECT_POSTGRES_DB"]) { $Values["SOUNDCONNECT_POSTGRES_DB"] } else { "soundconnect" }
    }
}

function Test-LocalBaseSchemaReady {
    $Connection = Get-LocalPostgresConnection
    $Query = "SELECT to_regclass('public.tbl_user') IS NOT NULL AND to_regclass('public.tbl_studio_profile') IS NOT NULL AND to_regclass('public.tbl_media_asset') IS NOT NULL AND to_regclass('public.tbl_role') IS NOT NULL AND to_regclass('public.tbl_permissions') IS NOT NULL;"
    $Output = & docker compose `
        --project-directory $ProjectRoot `
        --env-file $EnvFile `
        exec -T postgres psql `
        -X -qAt `
        -U $Connection.Username `
        -d $Connection.Database `
        -c $Query 2>$null
    return $LASTEXITCODE -eq 0 -and (($Output -join "").Trim() -eq "t")
}

function Test-LocalComposeServiceHealthy([string]$Service) {
    $ContainerIds = & docker compose `
        --project-directory $ProjectRoot `
        --env-file $EnvFile `
        ps --quiet $Service 2>$null
    $ComposeExitCode = $LASTEXITCODE
    $ContainerId = @($ContainerIds | Where-Object { $_ } | Select-Object -First 1)
    if ($ComposeExitCode -ne 0 -or $ContainerId.Count -eq 0) {
        return $false
    }

    $HealthStatus = & docker inspect `
        --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' `
        $ContainerId[0] 2>$null
    $InspectExitCode = $LASTEXITCODE
    return $InspectExitCode -eq 0 -and (($HealthStatus -join "").Trim() -eq "healthy")
}

function Wait-LocalComposeServicesHealthy(
    [string[]]$Services,
    [int]$TimeoutSeconds = 420
) {
    Write-Host "Waiting for healthy services: $($Services -join ', ')" -ForegroundColor Cyan
    $Deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    while ([DateTime]::UtcNow -lt $Deadline) {
        $Unhealthy = @($Services | Where-Object { -not (Test-LocalComposeServiceHealthy $_) })
        if ($Unhealthy.Count -eq 0) {
            Write-Host "Required services are healthy." -ForegroundColor Green
            return
        }
        Start-Sleep -Seconds 2
    }

    & docker compose --project-directory $ProjectRoot --env-file $EnvFile ps
    throw "Services did not become healthy within ${TimeoutSeconds}s: $($Services -join ', ')"
}

function Sync-LocalStudioSchema {
    if (-not (Test-Path -LiteralPath $StudioSchemaPath)) {
        throw "Local Studio schema source is missing: $StudioSchemaPath"
    }
    if (-not (Test-LocalBaseSchemaReady)) {
        throw "Local base schema is not ready; run '.\\dev.cmd up' once before using an IDE-only backend."
    }

    $Connection = Get-LocalPostgresConnection
    Write-Host "Synchronizing local Studio schema..." -ForegroundColor Cyan
    Get-Content -Raw -LiteralPath $StudioSchemaPath | & docker compose `
        --project-directory $ProjectRoot `
        --env-file $EnvFile `
        exec -T postgres psql `
        -X -v ON_ERROR_STOP=1 `
        -U $Connection.Username `
        -d $Connection.Database
    if ($LASTEXITCODE -ne 0) {
        throw "Local Studio schema synchronization failed with exit code $LASTEXITCODE."
    }
    Write-Host "Local Studio schema is ready." -ForegroundColor Green
    return $true
}

function Import-DotEnv([string]$Path) {
    foreach ($Line in Get-Content -LiteralPath $Path) {
        $Trimmed = $Line.Trim()
        if (-not $Trimmed -or $Trimmed.StartsWith("#")) {
            continue
        }

        $Pair = $Trimmed.Split("=", 2)
        if ($Pair.Count -ne 2 -or -not $Pair[0].Trim()) {
            throw "Invalid entry in ${Path}: $Line"
        }

        $Value = $Pair[1].Trim()
        if ($Value.Length -ge 2 -and (($Value.StartsWith('"') -and $Value.EndsWith('"')) -or ($Value.StartsWith("'") -and $Value.EndsWith("'")))) {
            $Value = $Value.Substring(1, $Value.Length - 2)
        }

        [Environment]::SetEnvironmentVariable($Pair[0].Trim(), $Value, "Process")
    }
}

Assert-Command "docker"
Assert-LocalEnv
Assert-ApiEnvironmentBoundary
Initialize-WorkerCredentials

Push-Location $ProjectRoot
try {
    switch ($Action) {
        "up" {
            Assert-NoPlaceholders
            # Hibernate owns the legacy local bootstrap, while the idempotent
            # Studio SQL owns PostgreSQL-only constraints, indexes and
            # backfills. Quiesce the worker, wait for the API to finish its full
            # Spring/Hibernate startup, stop request traffic, then reconcile
            # Studio before workers and normal test traffic start.
            Invoke-Compose @("stop", "media-worker")
            Invoke-Compose @("up", "--build", "--detach", "postgres", "rabbitmq", "redis", "backend")
            Wait-LocalComposeServicesHealthy @("postgres", "rabbitmq", "redis", "backend")
            if (-not (Test-LocalBaseSchemaReady)) {
                throw "The backend is healthy, but the required local base schema is incomplete."
            }
            Invoke-Compose @("stop", "backend")
            [void](Sync-LocalStudioSchema)
            Invoke-Compose @("up", "--build", "--detach")
            Wait-LocalComposeServicesHealthy @("postgres", "rabbitmq", "redis", "backend", "media-worker")
            Invoke-Compose @("ps")
        }
        "idea" {
            Assert-NoPlaceholders
            Invoke-Compose @("up", "--detach", "postgres", "rabbitmq", "redis")
            Invoke-Compose @("stop", "backend", "media-worker")
            [void](Sync-LocalStudioSchema)
            Write-Host "Infrastructure is ready. Compose API/native worker are stopped; start SoundConnectApplication from IntelliJ." -ForegroundColor Green
        }
        "infra" {
            Assert-NoPlaceholders
            Invoke-Compose @("up", "--detach", "postgres", "rabbitmq", "redis")
            Invoke-Compose @("ps")
        }
        "boot" {
            Assert-NoPlaceholders
            Invoke-Compose @("up", "--detach", "postgres", "rabbitmq", "redis")
            Invoke-Compose @("stop", "backend", "media-worker")
            Import-DotEnv $EnvFile
            & (Join-Path $ProjectRoot "gradlew.bat") bootRun
            if ($LASTEXITCODE -ne 0) {
                throw "Gradle bootRun failed with exit code $LASTEXITCODE."
            }
        }
        "down" {
            Invoke-Compose @("down", "--remove-orphans")
        }
        "logs" {
            $Arguments = @("logs", "--follow", "--tail", "200")
            if ($Service) {
                $Arguments += $Service
            }
            Invoke-Compose $Arguments
        }
        "ps" {
            Invoke-Compose @("ps")
        }
        "config" {
            Invoke-Compose @("config", "--quiet")
            Write-Host "Compose configuration is valid." -ForegroundColor Green
        }
        "reset-local" {
            if (-not $Force) {
                throw "This permanently deletes local PostgreSQL, Redis, and RabbitMQ data. Run: .\dev.cmd reset-local -Force"
            }

            Assert-NoPlaceholders
            Invoke-Compose @("down", "--volumes", "--remove-orphans")
            Invoke-Compose @("up", "--build", "--detach", "postgres", "rabbitmq", "redis", "backend")
            Wait-LocalComposeServicesHealthy @("postgres", "rabbitmq", "redis", "backend")
            if (-not (Test-LocalBaseSchemaReady)) {
                throw "The backend is healthy, but the required local base schema is incomplete."
            }
            Invoke-Compose @("stop", "backend")
            [void](Sync-LocalStudioSchema)
            Invoke-Compose @("up", "--build", "--detach")
            Wait-LocalComposeServicesHealthy @("postgres", "rabbitmq", "redis", "backend", "media-worker")
            Invoke-Compose @("ps")
        }
    }
}
finally {
    Pop-Location
}
